//! Golden-master parity harness for the deterministic economic turn.
//!
//! This integration-test file loads a Python-generated save state, runs the
//! Rust `run_economic_turn` function, and compares the resulting `Treasury` and
//! `MacroData` against the expected "Turn + 1" output generated by the Python
//! engine. For Target 2 Part 1 the only ported formula is the sector-level GDP
//! share update from employment (`economy/indicators/core.py`); the harness
//! proves the Rust math matches the Python logic with hardcoded expected values.

use sim_engine::economy::indicators::{run_economic_turn, update_gdp_shares_from_employment, CountryTurnCtx, ParityResult};
use sim_engine::economy::market::{GlobalMarket, MarketOrders, MarketSignal};
use sim_engine::economy::process_building_cycle;
use sim_engine::economy::process_demographics_and_labor;
use sim_engine::economy::resolve_market_prices;
use sim_engine::entities::{ActiveProductionMethod, Building, Company};
use sim_engine::engine::{run_turn_in_memory, InMemoryTurnContext};
use sim_engine::io::save_manager::{load_game_state, load_country_data};
use sim_engine::registries::enums::Commodity;
use sim_engine::registries::Registries;
use sim_engine::state::{Country, Currency, GameState, MacroData, Politics, TaxRates, TradePolicy, Treasury};
use std::collections::HashMap;
use std::path::Path;

/// Floating-point equality tolerance for golden-master parity comparisons.
const EPSILON: f64 = 1e-9;

/// Asserts that two `f64` values are within `epsilon` of each other.
macro_rules! assert_f64_eq {
    ($a:expr, $b:expr, $epsilon:expr) => {
        let a = $a;
        let b = $b;
        let epsilon = $epsilon;
        assert!(
            (a - b).abs() < epsilon,
            "assertion failed: |{} - {}| = {} >= epsilon {}",
            a,
            b,
            (a - b).abs(),
            epsilon
        );
    };
}

/// Path to the Python engine's `data/` directory, relative to this crate.
fn data_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("data")
}

/// Loads the first country from the real Python save as an owned value.
///
/// The caller must create the [`CountryTurnCtx`] in its own scope so the
/// mutable borrow outlives the context.
fn load_first_country() -> (String, Country) {
    let dir = data_dir();
    let game_state = load_game_state(&dir).expect("failed to load Python game state");
    game_state
        .countries
        .into_iter()
        .next()
        .expect("no countries in save")
}

/// Builds a hardcoded `turn_0` country used for the first parity test.
///
/// The sector map contains two sectors whose `employment` values sum to
/// 1000, so the Python `_calculate_gdp_shares_from_employment` will set the
/// GDP shares to 0.3 and 0.7 respectively.
fn hardcoded_turn_0_country() -> Country {
    use sim_engine::registries::enums::Sector;
    use sim_engine::state::treasury::SectorShare;

    Country::test_builder()
        .with_name("Iliria")
        .configure_treasury(|t| {
            t.gdp = 1000.0;
            t.population = 1000;
            t.nominal_budget = 10.0;
            t.liquid_reserves = 0.0;
            t.citizen_savings = 0.0;
            t.private_capital = 0.0;
            t.infrastructure_level = 1.0;
            t.energy_infrastructure = 1.0;
            t.stock_market.index = 100.0;
            t.stock_market.confidence = 50.0;
            t.stock_market.last_change = 0.0;
            t.allocations.industry = 0.14;
            t.allocations.education_propaganda = 0.14;
            t.allocations.healthcare = 0.14;
            t.allocations.infrastructure_transport = 0.14;
            t.allocations.social_programs = 0.15;
            t.allocations.agriculture_rural = 0.15;
            t.allocations.armed_forces = 0.14;
            t.black_ops_budget = 0.0;
            t.sectors.insert(
                Sector::Agriculture,
                SectorShare {
                    gdp_share: 0.0,
                    crisis_vulnerability: None,
                    active_method: None,
                    extra: {
                        let mut map = serde_json::Map::new();
                        map.insert("employment".to_string(), serde_json::json!(300));
                        map
                    },
                },
            );
            t.sectors.insert(
                Sector::HeavyIndustry,
                SectorShare {
                    gdp_share: 0.0,
                    crisis_vulnerability: None,
                    active_method: None,
                    extra: {
                        let mut map = serde_json::Map::new();
                        map.insert("employment".to_string(), serde_json::json!(700));
                        map
                    },
                },
            );
            t.science.innovation_points = 0.0;
            t.science.researching = None;
            t.science.discovered = Vec::new();
            t.science.base_innovativeness = 0.0;
            t.last_balance_log = String::new();
        })
        .configure_macro_indicators(|m| {
            m.inflation = 0.0;
            m.gini = 0.0;
            m.social_unrest = 0.0;
            m.wealth_bracket = sim_engine::registries::enums::WealthBracket::High;
            m.productivity = 1.0;
            m.currency = "ILI".to_string();
            m.energy_mix.coal = 0.0;
            m.energy_mix.natural_gas = 0.0;
            m.energy_mix.uranium = 0.0;
            m.energy_mix.renewables = 1.0;
            m.average_wage = 1.0;
            m.culture = "Iliria".to_string();
            m.cultural_group = String::new();
            m.religion = String::new();
        })
        .configure_tax_rates(|t| {
            t.income_tax.rate = 0.0;
            t.income_tax.structure = "linear".to_string();
            t.corporate_tax = 0.0;
            t.public_debt.current_debt = 0.0;
            t.public_debt.interest_rate = 0.0;
        })
        .build()
}

#[test]
fn gdp_share_parity_against_hardcoded_expected() {
    let reg = Registries::native_only();
    let mut country = hardcoded_turn_0_country();
    let mut ctx = CountryTurnCtx {
        country_name: country.name.clone(),
        turn: 0,
        year: 2020,
        registries: &reg,
        country: &mut country,
        buildings: Vec::new(),
        market_prices: std::collections::HashMap::new(),
    };

    update_gdp_shares_from_employment(&mut ctx);

    // Turn 1 expected values (computed by the Python `_calculate_gdp_shares_from_employment`).
    let sectors = &ctx.country.budget.sectors;
    let rolnictwo = &sectors[&sim_engine::registries::enums::Sector::Agriculture];
    let przemysl_ciezki = &sectors[&sim_engine::registries::enums::Sector::HeavyIndustry];

    assert_f64_eq!(rolnictwo.gdp_share, 0.3, EPSILON);
    assert_f64_eq!(przemysl_ciezki.gdp_share, 0.7, EPSILON);
}

#[test]
fn harness_loads_real_save_and_runs_turn_1() {
    let reg = Registries::native_only();
    let (name, mut country) = load_first_country();
    let mut ctx = CountryTurnCtx {
        country_name: name,
        turn: 0,
        year: 2020,
        registries: &reg,
        country: &mut country,
        buildings: Vec::new(),
        market_prices: std::collections::HashMap::new(),
    };
    let result = run_economic_turn(&mut ctx).expect("turn function should not error");

    // No golden-master snapshot exists yet for the full turn.
    assert_eq!(result, ParityResult::MissingExpected);
}

#[test]
fn harness_can_load_any_country_by_name() {
    let dir = data_dir();
    let mut country = load_country_data(&dir, "Anglia")
        .expect("expected Anglia to be present in the test save");

    let reg = Registries::native_only();
    let mut ctx = CountryTurnCtx {
        country_name: country.name.clone(),
        turn: 0,
        year: 2020,
        registries: &reg,
        country: &mut country,
        buildings: Vec::new(),
        market_prices: std::collections::HashMap::new(),
    };
    let result = run_economic_turn(&mut ctx).expect("turn function should not error");
    assert_eq!(result, ParityResult::MissingExpected);
}

#[test]
fn fractional_reserve_parity_test() {
    use sim_engine::registries::enums::Sector;
    use sim_engine::entities::{LegalForm, JointStockData};
    use sim_engine::state::banking::{BankBalanceSheet, BankType};
    use sim_engine::state::process_banking_turn;

    let balance_sheet = BankBalanceSheet {
        reserves_at_central_bank: 100_000.0,
        deposits: 1_000_000.0,
        tier_1_capital: 10_000_000.0,
        ..Default::default()
    };

    let mut bank_company = Company::new(
        "TEST-1".to_string(),
        "Test Bank".to_string(),
        Sector::Banking,
        LegalForm::JointStockCompany(JointStockData::default()),
        0.0,
        0.0,
        0,
    );
    bank_company.bank_type = Some(BankType::Commercial);
    bank_company.balance_sheet = Some(balance_sheet);

    // Borrower company: needs working capital (worker_capacity * 1000 - available_cash)
    let mut borrower = Company::new(
        "BORROW-1".to_string(),
        "Borrower Corp".to_string(),
        Sector::HeavyIndustry,
        LegalForm::JointStockCompany(JointStockData::default()),
        1_000_000.0, // fixed_capital = collateral for loan
        100_000.0,   // liquid_capital
        600,          // worker_capacity = 600 → needs 600,000 working capital
    );
    borrower.available_cash = 100_000.0; // Has 100k, needs 500k more (within per-loan cap)

    let mut companies = vec![bank_company, borrower];

    let mut country = Country::test_builder()
        .with_name("Testlandia")
        .configure_treasury(|t| {
            t.gdp = 1000.0;
            t.population = 1000;
            t.nominal_budget = 10.0;
            t.liquid_reserves = 0.0;
            t.citizen_savings = 0.0;
            t.private_capital = 0.0;
            t.infrastructure_level = 1.0;
            t.energy_infrastructure = 1.0;
            t.stock_market.index = 100.0;
            t.stock_market.confidence = 50.0;
            t.stock_market.last_change = 0.0;
            t.allocations.industry = 0.14;
            t.allocations.education_propaganda = 0.14;
            t.allocations.healthcare = 0.14;
            t.allocations.infrastructure_transport = 0.14;
            t.allocations.social_programs = 0.15;
            t.allocations.agriculture_rural = 0.15;
            t.allocations.armed_forces = 0.14;
            t.black_ops_budget = 0.0;
            t.science.innovation_points = 0.0;
            t.science.researching = None;
            t.science.discovered = Vec::new();
            t.science.base_innovativeness = 0.0;
            t.last_balance_log = String::new();
        })
        .configure_macro_indicators(|m| {
            m.inflation = 0.0;
            m.gini = 0.0;
            m.social_unrest = 0.0;
            m.wealth_bracket = sim_engine::registries::enums::WealthBracket::High;
            m.productivity = 1.0;
            m.currency = "TST".to_string();
            m.energy_mix.coal = 0.0;
            m.energy_mix.natural_gas = 0.0;
            m.energy_mix.uranium = 0.0;
            m.energy_mix.renewables = 1.0;
            m.average_wage = 1.0;
            m.culture = "Testlandian".to_string();
            m.cultural_group = String::new();
            m.religion = String::new();
        })
        .configure_tax_rates(|t| {
            t.income_tax.rate = 0.0;
            t.income_tax.structure = "linear".to_string();
            t.corporate_tax = 0.0;
            t.public_debt.current_debt = 0.0;
            t.public_debt.interest_rate = 0.0;
        })
        .build();

    let _result = process_banking_turn(&mut country, &mut companies, 0);

    let bs = companies[0].balance_sheet.as_ref().expect("bank should have balance sheet");
    // Borrower needs 500,000 (600 * 1000 - 100,000), within the per-loan cap of 500,000.
    let total_loans: f64 = bs.loans_issued.iter().map(|l| l.outstanding_balance).sum();
    assert_f64_eq!(total_loans, 500_000.0, EPSILON);
}

#[test]
fn labor_demographics_parity_test() {
    let mut country = Country::test_builder()
        .with_name("Testlandia")
        .configure_treasury(|t| {
            t.gdp = 1000.0;
            t.population = 5_000_000;
            t.nominal_budget = 10.0;
            t.liquid_reserves = 0.0;
            t.citizen_savings = 0.0;
            t.private_capital = 0.0;
            t.infrastructure_level = 1.0;
            t.energy_infrastructure = 1.0;
            t.stock_market.index = 100.0;
            t.stock_market.confidence = 50.0;
            t.stock_market.last_change = 0.0;
            t.allocations.industry = 0.14;
            t.allocations.education_propaganda = 0.14;
            t.allocations.healthcare = 0.14;
            t.allocations.infrastructure_transport = 0.14;
            t.allocations.social_programs = 0.15;
            t.allocations.agriculture_rural = 0.15;
            t.allocations.armed_forces = 0.14;
            t.black_ops_budget = 0.0;
            t.science.innovation_points = 0.0;
            t.science.researching = None;
            t.science.discovered = Vec::new();
            t.science.base_innovativeness = 0.0;
            t.last_balance_log = String::new();
        })
        .configure_macro_indicators(|m| {
            m.inflation = 0.0;
            m.gini = 0.0;
            m.social_unrest = 0.0;
            m.wealth_bracket = sim_engine::registries::enums::WealthBracket::High;
            m.productivity = 1.0;
            m.currency = "TST".to_string();
            m.energy_mix.coal = 0.0;
            m.energy_mix.natural_gas = 0.0;
            m.energy_mix.uranium = 0.0;
            m.energy_mix.renewables = 1.0;
            m.average_wage = 1000.0;
            m.culture = "Testlandian".to_string();
            m.cultural_group = "Germanic".to_string();
            m.religion = "Protestantism".to_string();
            m.demographics.birth_rate = 1.05;
            m.demographics.death_rate = 0.710823192977059;
            m.demographics.net_migration = 0.0;
            m.demographics.age_groups.children = 0.25;
            m.demographics.age_groups.adults = 0.6;
            m.demographics.age_groups.elderly = 0.15;
            m.demographics.gender.male = 0.5;
            m.demographics.gender.female = 0.5;
            m.demographics.ethnic_composition.insert("Testlandian".to_string(), 0.94);
            m.demographics.ethnic_composition.insert("Other".to_string(), 0.06);
            m.demographics.religious_composition.insert("Protestantism".to_string(), 1.0);
            m.demographics.education.brak = 0.1;
            m.demographics.education.podstawowe = 0.6;
            m.demographics.education.srednie.insert("Technical".to_string(), 0.0);
            m.demographics.education.wyzsze.insert("General".to_string(), 0.3);
            m.labor_market.labor_force_participation = 60.0;
            m.labor_market.employed_total = 0.0;
            // Add health statistics to extra map for process_demographics_and_labor
            let mut health_stats = serde_json::Map::new();
            health_stats.insert("baza_infrastruktury_medycznej".to_string(), serde_json::json!(10.0));
            health_stats.insert("jakosc_sluzby_zdrowia".to_string(), serde_json::json!(50.0));
            health_stats.insert("zgony_w_pracy".to_string(), serde_json::json!(0.0));
            m.extra.insert("statystyki_zdrowotne".to_string(), serde_json::Value::Object(health_stats));
            // Add politics to extra map
            let mut politics = serde_json::Map::new();
            politics.insert("prawo_emancypacji".to_string(), serde_json::json!("Ograniczone Głosowanie"));
            politics.insert("prawo_obywatelskie".to_string(), serde_json::json!("Asymilacja 5 lat"));
            politics.insert("prawo_pracy".to_string(), serde_json::json!("Wolny Rynek"));
            politics.insert("agencja_pracy_aktywna".to_string(), serde_json::json!(false));
            politics.insert("tarcza_energetyczna".to_string(), serde_json::json!(false));
            m.extra.insert("polityka".to_string(), serde_json::Value::Object(politics));
            // Add crime statistics
            let mut crime = serde_json::Map::new();
            crime.insert("zbrodnie".to_string(), serde_json::json!(0.0));
            crime.insert("indeks_bezpieczenstwa".to_string(), serde_json::json!(80.0));
            m.extra.insert("przestepczosc".to_string(), serde_json::Value::Object(crime));
        })
        .configure_tax_rates(|t| {
            t.income_tax.rate = 0.0;
            t.income_tax.structure = "linear".to_string();
            t.corporate_tax = 0.0;
            t.public_debt.current_debt = 0.0;
            t.public_debt.interest_rate = 0.0;
        })
        .build();

    let reg = Registries::native_only();
    let mut ctx = CountryTurnCtx {
        country_name: country.name.clone(),
        turn: 0,
        year: 2020,
        registries: &reg,
        country: &mut country,
        buildings: Vec::new(),
        market_prices: std::collections::HashMap::new(),
    };

    process_demographics_and_labor(&mut ctx);

    let m = &ctx.country.macro_indicators;
    assert_eq!(ctx.country.budget.population, 5_021_708);
    assert_f64_eq!(m.demographics.last_births, 47_250.0, EPSILON);
    assert_f64_eq!(m.demographics.last_deaths, 25_541.15964885295, EPSILON);
    assert_f64_eq!(m.demographics.last_migration, 0.0, EPSILON);
    assert_f64_eq!(m.demographics.age_groups.children, 0.24173378132010193, EPSILON);
    assert_f64_eq!(m.demographics.age_groups.adults, 0.5992500471311345, EPSILON);
    assert_f64_eq!(m.demographics.age_groups.elderly, 0.15901617154876369, EPSILON);
    assert_f64_eq!(m.labor_market.unemployment_rate, 100.0, EPSILON);
    assert_f64_eq!(m.labor_market.unemployment_structure.friction, 0.03, EPSILON);
    assert_f64_eq!(m.labor_market.unemployment_structure.cyclical, 0.582, EPSILON);
    assert_f64_eq!(m.labor_market.unemployment_structure.structural, 0.388, EPSILON);
    assert_f64_eq!(m.labor_market.poverty_pool_percent, 0.2328, EPSILON);
    assert_f64_eq!(m.labor_market.expert_tier.supply, 765_000.0, EPSILON);
    assert_f64_eq!(m.labor_market.skilled_tier.supply, 1_710_000.0, EPSILON);
    assert_f64_eq!(m.labor_market.unskilled_tier.supply, 300_000.0, EPSILON);
    assert_f64_eq!(m.labor_market.expert_tier.wage, 604.5, EPSILON);
    assert_f64_eq!(m.labor_market.skilled_tier.wage, 302.25, EPSILON);
    assert_f64_eq!(m.labor_market.unskilled_tier.wage, 201.5, EPSILON);
    assert_f64_eq!(m.average_wage, 201.5, EPSILON);
}

#[test]
fn production_cycle_parity_test() {
    let registries = Registries::native_only();
    let mut building = Building {
        name: "Cementownia".to_string(),
        worker_capacity: 2000,
        current_employment: 1600,
        scale_factor: 3,
        condition: 1.0,
        active_method: ActiveProductionMethod {
            year: 1880,
            experts_ratio: 0.0515,
            skilled_ratio: 0.2784,
            basic_ratio: 0.6701,
            efficiency: 1.0,
            inputs: [
                (Commodity::Limestone, 10.0),
                (Commodity::HardCoal, 5.0),
            ]
            .into_iter()
            .collect(),
            outputs: [(Commodity::Cement, 3000.0)].into_iter().collect(),
            active_methods: Default::default(),
            active_blueprint: None,
            extra: Default::default(),
        },
        ..Default::default()
    };

    let mut market_orders = MarketOrders::default();
    let result = process_building_cycle(
        &mut building,
        &mut market_orders,
        &std::collections::HashMap::new(),
        100.0,
        2020,
        &registries,
        0.0,
    );

    let scale = 4800.0 / 1000.0;

    // Inputs consumed per 1000 workers scaled by employment.
    assert_f64_eq!(result.inputs_consumed[&Commodity::Limestone], 10.0 * scale, EPSILON);
    assert_f64_eq!(
        result.inputs_consumed[&Commodity::HardCoal],
        5.0 * scale,
        EPSILON
    );
    assert_f64_eq!(result.outputs_produced[&Commodity::Cement], 3000.0 * scale, EPSILON);

    // Market orders must mirror the same amounts.
    assert_f64_eq!(market_orders.get(Commodity::Limestone).buy, 10.0 * scale, EPSILON);
    assert_f64_eq!(market_orders.get(Commodity::HardCoal).buy, 5.0 * scale, EPSILON);
    assert_f64_eq!(market_orders.get(Commodity::Cement).sell, 3000.0 * scale, EPSILON);

    // Wages are paid on all employees using the tier multipliers.
    let expected_wage_multiplier =
        0.0515 * 3.0 + 0.2784 * 2.0 + 0.6701 * 1.0;
    assert_f64_eq!(result.wages_paid, 4800.0 * expected_wage_multiplier * 100.0, EPSILON);
}

#[test]
fn market_clearing_parity_test() {
    let data_dir = data_dir();
    let mut country = load_country_data(&data_dir, "Anglia").unwrap();

    let fuel = Commodity::Fuels;

    let mut trade_policy = TradePolicy::default();
    trade_policy.import_tariffs.insert(fuel, 0.20);
    country.trade_policy = trade_policy;

    let mut orders = MarketOrders::default();
    orders.add_buy(fuel, 1000.0);
    orders.add_sell(fuel, 200.0);

    let mut global = GlobalMarket::new();
    global.base_prices.insert(fuel, 100.0);
    global.net_surplus.insert(fuel, 1000.0);

    let prices = resolve_market_prices(&orders, &country, &global);

    assert_f64_eq!(prices[&fuel], 120.0, EPSILON);
}

#[test]
fn treasury_balance_parity_test() {
    let mut country = Country::test_builder()
        .with_name("Testlandia")
        .configure_treasury(|t| {
            t.gdp = 0.0;
            t.population = 1;
            t.nominal_budget = 0.0;
            t.liquid_reserves = 100_000.0;
            t.citizen_savings = 0.0;
            t.private_capital = 0.0;
            t.infrastructure_level = 1.0;
            t.energy_infrastructure = 1.0;
            t.stock_market.index = 100.0;
            t.stock_market.confidence = 50.0;
            t.stock_market.last_change = 0.0;
            t.allocations.industry = 0.0;
            t.allocations.education_propaganda = 0.0;
            t.allocations.healthcare = 0.0;
            t.allocations.infrastructure_transport = 0.0;
            t.allocations.social_programs = 0.0;
            t.allocations.agriculture_rural = 0.0;
            t.allocations.armed_forces = 0.0;
            t.black_ops_budget = 0.0;
            t.science.innovation_points = 0.0;
            t.science.researching = None;
            t.science.discovered = Vec::new();
            t.science.base_innovativeness = 0.0;
            t.last_balance_log = String::new();
        })
        .configure_macro_indicators(|m| {
            m.inflation = 0.0;
            m.gini = 0.0;
            m.social_unrest = 0.0;
            m.wealth_bracket = sim_engine::registries::enums::WealthBracket::High;
            m.productivity = 1.0;
            m.currency = "TST".to_string();
            m.energy_mix.coal = 0.0;
            m.energy_mix.natural_gas = 0.0;
            m.energy_mix.uranium = 0.0;
            m.energy_mix.renewables = 1.0;
            m.average_wage = 1000.0;
            m.culture = "Testlandian".to_string();
            m.cultural_group = "Germanic".to_string();
            m.religion = "Protestantism".to_string();
            m.labor_market.expert_tier.employed = 0.0;
            m.labor_market.expert_tier.wage = 0.0;
            m.labor_market.skilled_tier.employed = 0.0;
            m.labor_market.skilled_tier.wage = 0.0;
            m.labor_market.unskilled_tier.employed = 1000.0;
            m.labor_market.unskilled_tier.wage = 1000.0;
        })
        .configure_tax_rates(|t| {
            t.income_tax.rate = 0.2;
            t.income_tax.structure = "linear".to_string();
            t.corporate_tax = 0.1;
            t.public_debt.current_debt = 2_000_000.0;
            t.public_debt.interest_rate = 0.05;
        })
        .build();

    let building = Building {
        owner_id: "COMP-1".to_string(),
        current_employment: 1000,
        last_profit: 500_000.0,
        ..Default::default()
    };

    let company = Company {
        id: "COMP-1".to_string(),
        name: "TestCorp".to_string(),
        available_cash: 500_000.0,
        ..Default::default()
    };
    let companies = vec![company];
    let buildings = vec![building];

    // Ensure citizen_savings can cover PIT (double-entry: PIT deducted from savings)
    country.budget.citizen_savings = 200_000.0;
    // Register a tax office so evasion is 0% (1 office > 0.1 required for 1 company)
    country.budget.tax_office_ids.push("TAX-1".to_string());

    let _tax_result = sim_engine::state::process_tax_collection_turn(
        &mut country,
        &companies,
        &buildings,
        0,
    );

    // Tax revenue should be PIT (1000 workers * 1000 wage * 0.2 = 200,000)
    // plus CIT (500,000 building profit * 0.1 = 50,000) = 250,000 total.
    assert_f64_eq!(_tax_result.total_revenue, 250_000.0, EPSILON);
    assert_f64_eq!(country.budget.liquid_reserves, 350_000.0, EPSILON);
}

/// Builds a minimal `Country` for the corporate and global-trade parity tests.
fn test_country(
    name: &str,
    gdp: f64,
    liquid_reserves: f64,
    currency: &str,
    productivity: f64,
    inflation: f64,
    corporate_tax: f64,
) -> Country {
    use sim_engine::registries::enums::Sector;
    use sim_engine::state::treasury::SectorShare;

    Country::test_builder()
        .with_name(name)
        .configure_treasury(|t| {
            t.gdp = gdp;
            t.population = 1000;
            t.nominal_budget = gdp;
            t.liquid_reserves = liquid_reserves;
            t.citizen_savings = 0.0;
            t.private_capital = 0.0;
            t.infrastructure_level = 1.0;
            t.energy_infrastructure = 1.0;
            t.stock_market.index = 100.0;
            t.stock_market.confidence = 50.0;
            t.stock_market.last_change = 0.0;
            t.allocations.industry = 0.14;
            t.allocations.education_propaganda = 0.14;
            t.allocations.healthcare = 0.14;
            t.allocations.infrastructure_transport = 0.14;
            t.allocations.social_programs = 0.15;
            t.allocations.agriculture_rural = 0.15;
            t.allocations.armed_forces = 0.14;
            t.black_ops_budget = 0.0;
            t.sectors.insert(
                Sector::Agriculture,
                SectorShare {
                    gdp_share: 0.5,
                    crisis_vulnerability: None,
                    active_method: None,
                    extra: serde_json::Map::new(),
                },
            );
            t.science.innovation_points = 0.0;
            t.science.researching = None;
            t.science.discovered = Vec::new();
            t.science.base_innovativeness = 0.0;
            t.last_balance_log = String::new();
        })
        .configure_macro_indicators(|m| {
            m.inflation = inflation;
            m.gini = 0.0;
            m.social_unrest = 0.0;
            m.wealth_bracket = sim_engine::registries::enums::WealthBracket::High;
            m.productivity = productivity;
            m.currency = currency.to_string();
            m.energy_mix.coal = 0.0;
            m.energy_mix.natural_gas = 0.0;
            m.energy_mix.uranium = 0.0;
            m.energy_mix.renewables = 1.0;
            m.average_wage = 1.0;
            m.culture = "Test".to_string();
            m.cultural_group = String::new();
            m.religion = String::new();
        })
        .configure_tax_rates(|t| {
            t.income_tax.rate = 0.12;
            t.income_tax.structure = "linear".to_string();
            t.corporate_tax = corporate_tax;
            t.public_debt.current_debt = 0.0;
            t.public_debt.interest_rate = 0.02;
        })
        .build()
}

/// Corporate restructuring parity test.
///
/// Mirrors the Python `test_restructuring.py` set-up: one profitable company
/// expands, one deeply insolvent company is restructured and its building
/// capacity is wiped.
#[test]
fn corporate_restructuring_parity_test() {
    let mut country = test_country("Testland", 100_000.0, 0.0, "TST", 1.0, 0.0, 0.2);

    let company_a = Company {
        id: "EXP-1".to_string(),
        name: "Expander".to_string(),
        building_ids: vec!["B1".to_string()],
        fixed_capital: 5_000.0,
        liquid_capital: 5_000.0,
        liabilities: 0.0,
        worker_capacity: 100,
        ..Default::default()
    };

    let building_a = Building {
        id: "B1".to_string(),
        owner_id: "EXP-1".to_string(),
        last_profit: 5_000.0,
        worker_capacity: 100,
        current_employment: 100,
        ..Default::default()
    };

    let company_b = Company {
        id: "RES-1".to_string(),
        name: "Restructured".to_string(),
        building_ids: vec!["B2".to_string()],
        fixed_capital: 5_000.0,
        liquid_capital: 0.0,
        liabilities: 6_000.0,
        worker_capacity: 100,
        ..Default::default()
    };

    let building_b = Building {
        id: "B2".to_string(),
        owner_id: "RES-1".to_string(),
        last_profit: -5_000.0,
        worker_capacity: 100,
        current_employment: 100,
        ..Default::default()
    };

    let mut companies = [company_a, company_b];
    let mut buildings = [building_a, building_b];

    sim_engine::corporate::process_companies(
        &mut companies,
        &mut buildings,
        &mut country,
        2020,
        &MarketSignal::default(),
        0,
    );

    let company_a = &companies[0];
    let company_b = &companies[1];
    let building_a = &buildings[0];
    let building_b = &buildings[1];

    // Profitable company expands: investment deducted from liquid_capital,
    // but fixed_capital/worker_capacity deferred to ConstructionProject completion.
    assert_f64_eq!(company_a.fixed_capital, 5_000.0, EPSILON);
    assert_f64_eq!(company_a.liquid_capital, 7_300.0, EPSILON);
    assert_f64_eq!(company_a.company_capital, 12_300.0, EPSILON);
    assert_eq!(company_a.worker_capacity, 100);
    assert_eq!(building_a.worker_capacity, 100);
    assert_eq!(building_a.current_employment, 100);
    // Expansion intent converted to ConstructionProject on the building
    assert!(building_a.active_project.is_some());

    // Insolvent company is wiped down to zero capacity and fixed capital.
    assert_f64_eq!(company_b.fixed_capital, 0.0, EPSILON);
    assert_f64_eq!(company_b.liquid_capital, 0.0, EPSILON);
    assert_f64_eq!(company_b.liabilities, 6_000.0, EPSILON);
    assert_eq!(company_b.worker_capacity, 0);
    assert_eq!(building_b.worker_capacity, 0);
    assert_eq!(building_b.current_employment, 0);

    // CIT collected from the profitable firm and private capital aggregated.
    assert_f64_eq!(country.budget.liquid_reserves, 950.0, EPSILON);
    assert_f64_eq!(country.budget.private_capital, 6_300.0, EPSILON);
}

/// Global trade balance parity test.
///
/// Two-country world: an export champion (high productivity) faces a lower
/// productivity importer. The Rust two-phase balancer should produce the same
/// exports/imports, reserve transfers, and currency shocks as the Python
/// `balance_international_trade` + `_force_global_trade_balance` sequence.
#[test]
fn global_trade_parity_test() {
    let mut state = GameState::new();

    let exporter = test_country("Exporter", 900_000.0, 1_000_000.0, "EXP", 2.0, 0.0, 0.0);
    let importer = test_country("Importer", 900_000.0, 1_000_000.0, "IMP", 1.0, 0.0, 0.0);

    state.countries.insert("Exporter".to_string(), exporter);
    state.countries.insert("Importer".to_string(), importer);

    state.currencies.insert(
        "EXP".to_string(),
        Currency {
            prefix: "EXP".to_string(),
            exchange_rate: 1.0,
            ..Default::default()
        },
    );
    state.currencies.insert(
        "IMP".to_string(),
        Currency {
            prefix: "IMP".to_string(),
            exchange_rate: 1.0,
            ..Default::default()
        },
    );

    let mut market_orders = MarketOrders::default();
    market_orders.add_sell(Commodity::Cement, 300_000.0);
    market_orders.add_buy(Commodity::Cement, 150_000.0);

    let global_market = GlobalMarket::default();
    let diplomacy = HashMap::new();

    let result = sim_engine::international::balance_global_trade(&mut state, &market_orders, &global_market, &diplomacy);

    assert_f64_eq!(result.total_trade_volume, 150_000.0, EPSILON);

    let exporter_delta = result
        .deltas
        .iter()
        .find(|d| d.country_name == "Exporter")
        .expect("exporter delta missing");
    let importer_delta = result
        .deltas
        .iter()
        .find(|d| d.country_name == "Importer")
        .expect("importer delta missing");

    assert_f64_eq!(exporter_delta.exports, 100_000.0, EPSILON);
    assert_f64_eq!(exporter_delta.imports, 50_000.0, EPSILON);
    assert_f64_eq!(exporter_delta.trade_balance, 50_000.0, EPSILON);

    assert_f64_eq!(importer_delta.exports, 50_000.0, EPSILON);
    assert_f64_eq!(importer_delta.imports, 100_000.0, EPSILON);
    assert_f64_eq!(importer_delta.trade_balance, -50_000.0, EPSILON);

    assert_f64_eq!(
        state.countries["Exporter"].budget.liquid_reserves,
        1_050_000.0,
        EPSILON
    );
    assert_f64_eq!(
        state.countries["Importer"].budget.liquid_reserves,
        950_000.0,
        EPSILON
    );

    // Currency shocks: surplus appreciates, deficit depreciates.
    assert_f64_eq!(state.currencies["EXP"].exchange_rate, 0.9, EPSILON);
    assert_f64_eq!(state.currencies["IMP"].exchange_rate, 1.15, EPSILON);
}

/// Full turn parity test.
///
/// Loads the real Python `turn_0` save, runs `run_turn`, and snapshots the
/// resulting country state. Use INSTA_UPDATE=always to update the baseline snapshot.
#[test]
fn full_turn_parity_test() {
    let data_dir = data_dir();
    let reg = Registries::native_only();
    let mut state = load_game_state(&data_dir).expect("failed to load turn_0");

    let mut ctx = InMemoryTurnContext::load_from_disk(&data_dir, &mut state)
        .expect("failed to load in-memory context");

    run_turn_in_memory(&mut state, &reg, &mut ctx)
        .expect("run_turn_in_memory should complete");

    let snapshot_path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("snapshots")
        .join("full_turn_parity_test__turn_1.snap");

    let mut actual: Vec<serde_json::Value> = state
        .countries
        .values()
        .map(|c| {
            serde_json::json!({
                "name": c.name,
                "gdp": c.budget.gdp,
                "population": c.budget.population,
                "liquid_reserves": c.budget.liquid_reserves,
                "private_capital": c.budget.private_capital,
            })
        })
        .collect();
    actual.sort_by(|a, b| a["name"].as_str().cmp(&b["name"].as_str()));

    let snapshot_content = serde_json::to_string_pretty(&actual).unwrap();
    
    std::fs::create_dir_all(snapshot_path.parent().unwrap()).unwrap();
    
    // Environment variable controls behavior
    if std::env::var("INSTA_UPDATE").as_deref() == Ok("always") {
        // Update mode: overwrite snapshot
        std::fs::write(&snapshot_path, snapshot_content).unwrap();
        eprintln!("Snapshot updated: {}", snapshot_path.display());
    } else {
        // Comparison mode: assert against baseline
        if snapshot_path.exists() {
            let expected = std::fs::read_to_string(&snapshot_path).unwrap();
            assert_eq!(
                snapshot_content, expected,
                "Snapshot mismatch. Run with INSTA_UPDATE=always to update."
            );
        } else {
            // First run: create snapshot
            std::fs::write(&snapshot_path, snapshot_content).unwrap();
            eprintln!("Snapshot created: {}", snapshot_path.display());
        }
    }
}

/// Political system parity test.
///
/// Loads a deterministic turn-0 country, runs the political phase and checks
/// that a parliament of 100 seats is allocated, the strongest party is placed
/// in power, the election cycle is reset, and the national policy bundle is
/// updated to match the ruling ideology. This mirrors the deterministic checks
/// in `politics/core.py`.
#[test]
fn political_system_parity_test() {
    let mut country = hardcoded_turn_0_country();
    country.budget.private_capital = 1000.0;
    country.budget.sectors.insert(
        sim_engine::registries::enums::Sector::LightIndustry,
        sim_engine::state::treasury::SectorShare {
            gdp_share: 0.2,
            crisis_vulnerability: None,
            active_method: None,
            extra: serde_json::Map::new(),
        },
    );
    country.budget.sectors.insert(
        sim_engine::registries::enums::Sector::LocalServices,
        sim_engine::state::treasury::SectorShare {
            gdp_share: 0.1,
            crisis_vulnerability: None,
            active_method: None,
            extra: serde_json::Map::new(),
        },
    );
    country.budget.sectors.insert(
        sim_engine::registries::enums::Sector::ExportServices,
        sim_engine::state::treasury::SectorShare {
            gdp_share: 0.1,
            crisis_vulnerability: None,
            active_method: None,
            extra: serde_json::Map::new(),
        },
    );
    country.budget.sectors.insert(
        sim_engine::registries::enums::Sector::PublicServices,
        sim_engine::state::treasury::SectorShare {
            gdp_share: 0.05,
            crisis_vulnerability: None,
            active_method: None,
            extra: serde_json::Map::new(),
        },
    );

    country.politics.election_method = "D'Hondt".to_string();
    country.politics.election_threshold = 5.0;
    country.politics.years_to_elections = 0;

    // Seat allocation does not depend on corporate actors; donations and dues
    // simply have no counterparties in this fixture.
    let mut companies = Vec::new();
    let mut unions = Vec::new();
    let messages = sim_engine::politics::process_political_year(&mut country, &mut companies, &mut unions, 2020);

    let total_seats: u32 = country.politics.parliament.values().sum();
    assert_eq!(total_seats, 100, "parliament must allocate exactly 100 seats");

    let strongest = country
        .politics
        .parliament
        .iter()
        .max_by(|a, b| a.1.cmp(b.1))
        .map(|(n, _)| n.clone())
        .unwrap_or_default();
    assert_eq!(
        country.politics.ruling_party, strongest,
        "ruling party must be the strongest parliamentary force"
    );

    assert_eq!(country.politics.years_to_elections, 4, "election cycle should reset");
    assert!(
        !country.politics.government_economic_school.is_empty(),
        "ruling ideology should set the government's economic school"
    );
    assert!(
        !country.politics.trade_doctrine.is_empty(),
        "ruling ideology should set the trade doctrine"
    );
    assert!(
        messages.iter().any(|m| m.contains("[WYBORY]")),
        "election message should be emitted"
    );
}

// ============================================================================
// THE GREAT GOLDEN MASTER INTEGRATION TEST
// Phase 17C: Full Simulation Survival Test (50+ turns)
// Validates that the engine can survive long-term simulation without
// macroeconomic collapse, memory leaks, or unhandled panics.
// ============================================================================

use std::fs as stdfs;
use sim_engine::io::entity_store::{DiskEntityStore, EntityStore};

/// Recursively copy a directory tree.
fn copy_dir_recursive(src: &Path, dst: &Path) {
    if !dst.exists() {
        stdfs::create_dir_all(dst).unwrap();
    }
    for entry in stdfs::read_dir(src).unwrap() {
        let entry = entry.unwrap();
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir_recursive(&src_path, &dst_path);
        } else {
            stdfs::copy(&src_path, &dst_path).unwrap();
        }
    }
}

/// Compute total M3 money supply proxy: sum of all countries' liquid_reserves
/// + citizen_savings + private_capital + GlobalMarket.offshore_capital.
fn compute_m3(state: &GameState, market: &GlobalMarket) -> f64 {
    let country_money: f64 = state.countries.values()
        .map(|c| c.budget.liquid_reserves + c.budget.citizen_savings + c.budget.private_capital)
        .sum();
    country_money + market.offshore_capital
}

/// Compute total global population across all countries.
fn compute_total_population(state: &GameState) -> u64 {
    state.countries.values()
        .map(|c| c.budget.population)
        .sum()
}

/// Load all companies for a country from disk using DiskEntityStore.
fn load_all_companies(data_dir: &Path, country: &str) -> Vec<Company> {
    let companies_dir = data_dir.join("entities").join(country).join("companies");
    if !companies_dir.exists() {
        return Vec::new();
    }
    let store = DiskEntityStore::<Company>::new(data_dir);
    let mut all = Vec::new();
    for entry in stdfs::read_dir(&companies_dir).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let sector = path.file_stem().and_then(|s| s.to_str()).unwrap_or("").to_string();
        if sector.is_empty() { continue; }
        if let Ok(loaded) = store.load_sector(country, &sector, None) {
            all.extend(loaded);
        }
    }
    all
}

/// Load market from disk (same logic as engine::turn::load_market but simplified).
fn load_market_for_test(data_dir: &Path) -> GlobalMarket {
    let path = data_dir.join("market.json");
    if !path.exists() {
        return GlobalMarket {
            base_prices: HashMap::new(),
            net_surplus: HashMap::new(),
            offshore_capital: 0.0,
            apostolic_see_ledger: sim_engine::economy::market::ApostolicSeeLedger::default(),
            supply_volume: HashMap::new(),
            demand_volume: HashMap::new(),
        };
    }
    let text = stdfs::read_to_string(&path).unwrap_or_default();
    let parsed: serde_json::Value = serde_json::from_str(&text).unwrap_or_default();
    let mut base_prices = HashMap::new();
    let mut net_surplus = HashMap::new();
    if let Some(prices) = parsed.get("prices").and_then(|v| v.as_object()) {
        for (key, value) in prices {
            if let Ok(commodity) = serde_json::from_str::<Commodity>(&format!("\"{}\"", key)) {
                if let Some(price) = value.as_f64() {
                    base_prices.insert(commodity, price);
                }
            }
        }
    }
    if let Some(orders) = parsed.get("orders").and_then(|v| v.as_object()) {
        for (key, value) in orders {
            if let Ok(commodity) = serde_json::from_str::<Commodity>(&format!("\"{}\"", key)) {
                if let Some(order) = value.as_object() {
                    let buy = order.get("buy").and_then(|v| v.as_f64()).unwrap_or(0.0);
                    let sell = order.get("sell").and_then(|v| v.as_f64()).unwrap_or(0.0);
                    net_surplus.insert(commodity, sell - buy);
                }
            }
        }
    }
    GlobalMarket {
        base_prices,
        net_surplus,
        offshore_capital: 0.0,
        apostolic_see_ledger: sim_engine::economy::market::ApostolicSeeLedger::default(),
        supply_volume: HashMap::new(),
        demand_volume: HashMap::new(),
    }
}

/// Count syncretic cultures across all countries.
fn count_syncretic_cultures(state: &GameState) -> usize {
    state.countries.values()
        .map(|c| {
            c.macro_indicators.demographics.ethnic_composition
                .keys()
                .filter(|k| k.starts_with("SYNCRETIC_"))
                .count()
        })
        .sum()
}

/// Check that religious composition sums to approximately 1.0 per country.
fn check_religious_composition(state: &GameState) -> bool {
    for country in state.countries.values() {
        let comp = &country.macro_indicators.demographics.religious_composition;
        if comp.is_empty() { continue; }
        let sum: f64 = comp.values().sum();
        if (sum - 1.0).abs() > 0.1 {
            return false;
        }
    }
    true
}

/// The Great Golden Master Integration Test.
///
/// Runs the engine for 50 continuous turns using the real Python save data
/// and validates that the simulated world remains economically stable.
#[test]
fn full_simulation_survival_test() {
    let original_data = data_dir();
    let temp_base = std::env::temp_dir().join("sim_engine_gm_test");
    
    // Clean up any previous run.
    if temp_base.exists() {
        stdfs::remove_dir_all(&temp_base).unwrap();
    }
    
    // Copy the real Python save to a temp directory.
    copy_dir_recursive(&original_data, &temp_base);
    
    let reg = Registries::native_only();
    let mut state = load_game_state(&temp_base).expect("failed to load game state");
    
    // Snapshot initial conditions.
    let initial_market = load_market_for_test(&temp_base);
    let initial_m3 = compute_m3(&state, &initial_market);
    let initial_pop = compute_total_population(&state);
    let initial_country_count = state.countries.len();
    
    eprintln!("=== GREAT GOLDEN MASTER INTEGRATION TEST ===");
    eprintln!("Countries: {}", initial_country_count);
    eprintln!("Initial M3 (money supply proxy): {:.2}", initial_m3);
    eprintln!("Initial total population: {}", initial_pop);
    eprintln!("Running 50 turns...");
    
    // Load in-memory context once (replaces per-turn disk I/O).
    let mut ctx = InMemoryTurnContext::load_from_disk(&temp_base, &mut state)
        .expect("failed to load in-memory context");

    // Run 50 continuous turns with persistence.
    const NUM_TURNS: u32 = 50;
    for turn in 0..NUM_TURNS {
        let result = run_turn_in_memory(&mut state, &reg, &mut ctx);

        if let Err(ref e) = result {
            panic!("run_turn_in_memory failed at turn {}: {:?}", turn, e);
        }

        // Save to disk so test helpers (load_market_for_test, load_all_companies) can read back.
        let global_orders = sim_engine::economy::market::MarketOrders::default();
        let trade_result = sim_engine::international::TradeBalanceResult::default();
        let _ = ctx.save_to_disk(&temp_base, &state, &global_orders, &trade_result);
        
        // Periodic checks every 10 turns.
        if (turn + 1) % 10 == 0 {
            let current_market = load_market_for_test(&temp_base);
            let current_m3 = compute_m3(&state, &current_market);
            let current_pop = compute_total_population(&state);
            
            eprintln!(
                "  Turn {} | M3: {:.2} | Pop: {} | Countries: {}",
                turn + 1,
                current_m3,
                current_pop,
                state.countries.len()
            );
            
            // === MONETARY CONSERVATION ===
            // M3 should not go to infinity (hyperinflation) or zero (deflationary black hole).
            // Allow generous bounds: 0.01x to 1000x of initial.
            assert!(
                current_m3 < initial_m3 * 1000.0,
                "Hyperinflation detected at turn {}: M3 = {:.2} (initial: {:.2})",
                turn + 1, current_m3, initial_m3
            );
            assert!(
                current_m3 > initial_m3 * 0.01,
                "Deflationary collapse at turn {}: M3 = {:.2} (initial: {:.2})",
                turn + 1, current_m3, initial_m3
            );
            
            // === DEMOGRAPHIC PHYSICS ===
            // Population should not collapse to zero or explode to infinity.
            assert!(
                current_pop > 0,
                "Global extinction at turn {}: population = 0",
                turn + 1
            );
            assert!(
                current_pop < initial_pop * 3,
                "Population explosion at turn {}: pop = {} (initial: {})",
                turn + 1, current_pop, initial_pop
            );
            
            // No country should have lost all its population.
            for (name, country) in &state.countries {
                assert!(
                    country.budget.population > 0,
                    "Country '{}' has zero population at turn {}",
                    name, turn + 1
                );
            }
            
            // Syncretic cultures must not exceed 3 per country.
            for (name, country) in &state.countries {
                let syncretic_count = country.macro_indicators.demographics.ethnic_composition
                    .keys()
                    .filter(|k| k.starts_with("SYNCRETIC_"))
                    .count();
                assert!(
                    syncretic_count <= 3,
                    "Country '{}' has {} syncretic cultures at turn {} (max 3)",
                    name, syncretic_count, turn + 1
                );
            }
            
            // Religious composition should sum to ~1.0 per country.
            assert!(
                check_religious_composition(&state),
                "Religious composition divergence at turn {}",
                turn + 1
            );
        }
    }
    
    // === FINAL ASSERTIONS AFTER 50 TURNS ===
    let final_market = load_market_for_test(&temp_base);
    let final_m3 = compute_m3(&state, &final_market);
    let final_pop = compute_total_population(&state);
    let total_syncretic = count_syncretic_cultures(&state);
    
    eprintln!("=== SIMULATION COMPLETE: 50 TURNS ===");
    eprintln!();
    
    // 1. MONETARY CONSERVATION
    eprintln!("--- Monetary Conservation ---");
    eprintln!("Initial M3: {:.2}", initial_m3);
    eprintln!("Final M3:   {:.2}", final_m3);
    eprintln!("M3 delta:   {:.2} ({:.1}%)", final_m3 - initial_m3, (final_m3 / initial_m3 - 1.0) * 100.0);
    assert!(
        final_m3 < initial_m3 * 1000.0,
        "Hyperinflation: final M3 = {:.2} (initial: {:.2})",
        final_m3, initial_m3
    );
    assert!(
        final_m3 > initial_m3 * 0.01,
        "Deflationary collapse: final M3 = {:.2} (initial: {:.2})",
        final_m3, initial_m3
    );
    
    // 2. B2C VIABILITY — check that companies still have cash.
    eprintln!();
    eprintln!("--- B2C Viability ---");
    let mut total_companies = 0;
    let mut companies_with_cash = 0;
    let mut total_company_cash = 0.0_f64;
    let mut banking_companies = 0;
    let mut banks_with_balance_sheet = 0;
    let mut banks_valid_reserves = 0;
    
    for country_name in state.countries.keys() {
        let companies = load_all_companies(&temp_base, country_name);
        for company in &companies {
            total_companies += 1;
            let cash = company.brokerage_account.as_ref()
                .map(|b| b.cash)
                .unwrap_or(company.available_cash);
            if cash > 0.0 {
                companies_with_cash += 1;
                total_company_cash += cash;
            }
            
            // Banking stability checks.
            if company.bank_type.is_some() {
                banking_companies += 1;
                if company.balance_sheet.is_some() {
                    banks_with_balance_sheet += 1;
                    let bs = company.balance_sheet.as_ref().unwrap();
                    if bs.reserves_at_central_bank >= 0.0 && bs.deposits >= 0.0 {
                        banks_valid_reserves += 1;
                    }
                }
            }
        }
    }
    
    eprintln!("Total companies: {}", total_companies);
    eprintln!("Companies with positive cash: {} ({:.1}%)", companies_with_cash,
        if total_companies > 0 { companies_with_cash as f64 / total_companies as f64 * 100.0 } else { 0.0 });
    eprintln!("Total company cash: {:.2}", total_company_cash);
    
    assert!(
        companies_with_cash > 0,
        "B2C viability failure: no companies have positive cash after 50 turns"
    );
    assert!(
        total_company_cash > 0.0,
        "B2C viability failure: total company cash is zero after 50 turns"
    );
    
    // 3. BANKING STABILITY
    eprintln!();
    eprintln!("--- Banking Stability ---");
    eprintln!("Banking companies: {}", banking_companies);
    eprintln!("Banks with balance sheet: {}", banks_with_balance_sheet);
    eprintln!("Banks with valid reserves: {}", banks_valid_reserves);
    
    if banking_companies > 0 {
        assert!(
            banks_with_balance_sheet > 0,
            "Banking stability failure: no banks have balance sheets"
        );
        assert!(
            banks_valid_reserves > 0,
            "Banking stability failure: no banks have valid (non-negative) reserves"
        );
    }
    
    // 4. DEMOGRAPHIC PHYSICS
    eprintln!();
    eprintln!("--- Demographic Physics ---");
    eprintln!("Initial population: {}", initial_pop);
    eprintln!("Final population:   {}", final_pop);
    eprintln!("Population delta:   {} ({:.1}%)",
        final_pop as i64 - initial_pop as i64,
        (final_pop as f64 / initial_pop as f64 - 1.0) * 100.0);
    eprintln!("Total syncretic cultures across all countries: {}", total_syncretic);
    
    assert!(final_pop > 0, "Global extinction: population reached 0");
    assert!(
        final_pop < initial_pop * 3,
        "Population explosion: {} (initial: {})",
        final_pop, initial_pop
    );
    
    // Syncretic culture cap verification.
    for (name, country) in &state.countries {
        let syncretic_count = country.macro_indicators.demographics.ethnic_composition
            .keys()
            .filter(|k| k.starts_with("SYNCRETIC_"))
            .count();
        assert!(
            syncretic_count <= 3,
            "Syncretic culture cap violated for '{}': {} (max 3)",
            name, syncretic_count
        );
    }
    
    // Religious composition sums to ~1.0.
    assert!(
        check_religious_composition(&state),
        "Religious composition divergence after 50 turns"
    );
    
    // 5. NO PANICS — if we reached here, the engine survived 50 turns without panicking.
    eprintln!();
    eprintln!("--- No Panics ---");
    eprintln!("Engine completed 50 turns without any panics or unhandled errors.");
    
    // 6. PER-COUNTRY MACROECONOMIC SUMMARY
    eprintln!();
    eprintln!("--- Per-Country Macroeconomic Summary (after 50 turns) ---");
    let mut country_summary: Vec<(String, f64, u64, f64, f64, f64)> = state.countries
        .iter()
        .map(|(name, c)| {
            (name.clone(), c.budget.gdp, c.budget.population,
             c.budget.liquid_reserves, c.budget.citizen_savings, c.budget.private_capital)
        })
        .collect();
    country_summary.sort_by(|a, b| a.0.cmp(&b.0));
    
    for (name, gdp, pop, reserves, savings, private) in &country_summary {
        eprintln!(
            "  {:<12} | GDP: {:>12.2} | Pop: {:>10} | Reserves: {:>12.2} | Savings: {:>12.2} | Private: {:>12.2}",
            name, gdp, pop, reserves, savings, private
        );
    }
    
    // 7. APOSTOLIC SEE LEDGER
    eprintln!();
    eprintln!("--- Apostolic See Ledger ---");
    eprintln!("Total remittances: {:.2}", final_market.apostolic_see_ledger.total_remittances);
    eprintln!("Global charity pool: {:.2}", final_market.apostolic_see_ledger.global_charity_pool);
    
    // Clean up temp directory.
    stdfs::remove_dir_all(&temp_base).ok();

    eprintln!();
    eprintln!("=== GREAT GOLDEN MASTER INTEGRATION TEST: PASSED ===");
}

// ═══════════════════════════════════════════════════════════════════════════════
// THE GREAT GOLDEN MASTER 2.0 — 100-TURN SURVIVAL TEST
// ═══════════════════════════════════════════════════════════════════════════════

/// Load all buildings for a country from disk (mirrors load_all_companies).
fn load_all_buildings(data_dir: &Path, country: &str) -> Vec<Building> {
    use sim_engine::io::entity_store::{DiskEntityStore, EntityStore};
    let buildings_dir = data_dir.join("entities").join(country).join("buildings");
    if !buildings_dir.exists() {
        return Vec::new();
    }
    let store = DiskEntityStore::<Building>::new(data_dir);
    let mut all = Vec::new();
    for entry in stdfs::read_dir(&buildings_dir).unwrap().flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("json") {
            continue;
        }
        let sector = path.file_stem().and_then(|s| s.to_str()).unwrap_or("").to_string();
        if sector.is_empty() { continue; }
        if let Ok(loaded) = store.load_sector(country, &sector, None) {
            all.extend(loaded);
        }
    }
    all
}

/// The Great Golden Master 2.0 — 100-Turn Survival Test.
///
/// Generates a **fresh** world (not the legacy Python save, which lacks banks),
/// runs the engine for 100 continuous turns, and validates:
///
/// 1. **Banking Integrity (CRITICAL):** commercial banks exist (`count > 0`),
///    have balance sheets, and reserves are non-negative. No vacuous passes.
/// 2. **Monetary Conservation:** M3 money supply stays within 0.01×–1000× of
///    initial. No hyperinflation or deflationary collapse.
/// 3. **Phase 19 Fixed Assets:** cohort caps are respected (no RAM bloat),
///    cohorts degrade over time, and maintenance services are being produced.
/// 4. **Phase 18 Demographics & Justice:** populations stay positive, class
///    savings don't drain to zero globally, shadow economy state processes
///    without creating negative money.
/// 5. **No Panics:** the engine completes 100 turns without panicking.
#[test]
fn golden_master_survival_100_turns_test() {
    use sim_engine::engine::{generate_world, GenerateOptions, StartYear};
    use sim_engine::registries::enums::Sector;

    let temp_base = std::env::temp_dir().join("sim_engine_gm2_test");

    // Clean up any previous run.
    if temp_base.exists() {
        stdfs::remove_dir_all(&temp_base).unwrap();
    }
    stdfs::create_dir_all(&temp_base).unwrap();

    // Generate a fresh world with 6 countries. This creates and saves banks.
    let reg = Registries::native_only();
    let options = GenerateOptions {
        country_count: 6,
        start_year: StartYear::Y1975,
    };
    let generated = generate_world(&temp_base, options, &reg)
        .expect("world generation should succeed");
    let mut state = generated.state;

    // Snapshot initial conditions.
    let initial_market = load_market_for_test(&temp_base);
    let initial_m3 = compute_m3(&state, &initial_market);
    let initial_pop = compute_total_population(&state);
    let initial_country_count = state.countries.len();

    // === CRITICAL: Verify banks exist right after generation ===
    let mut initial_bank_count = 0;
    for country_name in state.countries.keys() {
        let companies = load_all_companies(&temp_base, country_name);
        for company in &companies {
            if company.bank_type.is_some() || company.sector == Sector::Banking {
                initial_bank_count += 1;
            }
        }
    }
    eprintln!("=== GREAT GOLDEN MASTER 2.0: 100-TURN SURVIVAL TEST ===");
    eprintln!("Countries: {}", initial_country_count);
    eprintln!("Initial M3: {:.2}", initial_m3);
    eprintln!("Initial population: {}", initial_pop);
    eprintln!("Initial bank count: {}", initial_bank_count);
    assert!(
        initial_bank_count > 0,
        "CRITICAL: No banks generated! The world generator must create banks. \
         Found {} banks across {} countries.",
        initial_bank_count, initial_country_count
    );

    eprintln!("Running 100 turns...");

    // Run 100 continuous turns with persistence.
    const NUM_TURNS: u32 = 100;
    let mut max_cohort_count: usize = 0;
    let mut max_m3_multiplier: f64 = 1.0;
    let mut min_m3_multiplier: f64 = 1.0;

    // Load in-memory context once (replaces per-turn disk I/O).
    let mut ctx = InMemoryTurnContext::load_from_disk(&temp_base, &mut state)
        .expect("failed to load in-memory context");

    for turn in 0..NUM_TURNS {
        let result = run_turn_in_memory(&mut state, &reg, &mut ctx);

        if let Err(ref e) = result {
            panic!("run_turn_in_memory failed at turn {}: {:?}", turn, e);
        }

        // Save to disk so test helpers can read back.
        let global_orders = sim_engine::economy::market::MarketOrders::default();
        let trade_result = sim_engine::international::TradeBalanceResult::default();
        let _ = ctx.save_to_disk(&temp_base, &state, &global_orders, &trade_result);

        // Periodic checks every 10 turns.
        if (turn + 1) % 10 == 0 {
            let current_market = load_market_for_test(&temp_base);
            let current_m3 = compute_m3(&state, &current_market);
            let current_pop = compute_total_population(&state);
            let m3_mult = current_m3 / initial_m3.max(1.0);
            max_m3_multiplier = max_m3_multiplier.max(m3_mult);
            min_m3_multiplier = if min_m3_multiplier == 1.0 { m3_mult } else { min_m3_multiplier.min(m3_mult) };

            eprintln!(
                "  Turn {:>3} | M3: {:>14.2} ({:.2}x) | Pop: {:>10} | Countries: {}",
                turn + 1, current_m3, m3_mult, current_pop, state.countries.len()
            );

            // === 1. MONETARY CONSERVATION ===
            assert!(
                current_m3 < initial_m3 * 1000.0,
                "Hyperinflation at turn {}: M3 = {:.2} ({:.1}x initial)",
                turn + 1, current_m3, m3_mult
            );
            assert!(
                current_m3 > initial_m3 * 0.01,
                "Deflationary collapse at turn {}: M3 = {:.2} ({:.4}x initial)",
                turn + 1, current_m3, m3_mult
            );

            // === 2. DEMOGRAPHIC PHYSICS ===
            assert!(current_pop > 0, "Global extinction at turn {}", turn + 1);
            assert!(
                current_pop < initial_pop * 3,
                "Population explosion at turn {}: {} (initial: {})",
                turn + 1, current_pop, initial_pop
            );

            // No country should have zero population.
            for (name, country) in &state.countries {
                assert!(
                    country.budget.population > 0,
                    "Country '{}' has zero population at turn {}",
                    name, turn + 1
                );
            }

            // === 3. BANKING INTEGRITY (every 10 turns) ===
            let mut bank_count = 0;
            let mut banks_with_bs = 0;
            let mut banks_valid_reserves = 0;
            let mut total_bank_deposits = 0.0_f64;
            let mut total_bank_reserves = 0.0_f64;

            for country_name in state.countries.keys() {
                let companies = load_all_companies(&temp_base, country_name);
                for company in &companies {
                    if company.bank_type.is_some() || company.sector == Sector::Banking {
                        bank_count += 1;
                        if let Some(ref bs) = company.balance_sheet {
                            banks_with_bs += 1;
                            total_bank_deposits += bs.deposits;
                            total_bank_reserves += bs.reserves_at_central_bank;
                            if bs.reserves_at_central_bank >= 0.0 && bs.deposits >= 0.0 {
                                banks_valid_reserves += 1;
                            }
                        }
                    }
                }
            }

            eprintln!(
                "    Banks: {} | w/BS: {} | valid reserves: {} | deposits: {:.0} | reserves: {:.0}",
                bank_count, banks_with_bs, banks_valid_reserves, total_bank_deposits, total_bank_reserves
            );

            // STRICT assertion — no vacuous pass!
            assert!(
                bank_count > 0,
                "BANKING COLLAPSE at turn {}: 0 banks detected across all countries. \
                 Banks must persist throughout the simulation.",
                turn + 1
            );
            assert!(
                banks_with_bs > 0,
                "BANKING FAILURE at turn {}: {} banks exist but none have balance sheets",
                turn + 1, bank_count
            );
            assert!(
                banks_valid_reserves > 0,
                "BANKING FAILURE at turn {}: no banks have valid (non-negative) reserves",
                turn + 1
            );

            // === 4. PHASE 19 FIXED ASSET COHORT CAPS ===
            let mut total_cohorts = 0;
            let mut buildings_with_cohorts = 0;
            let mut total_cohort_units = 0.0_f64;
            let cohort_cap = 12; // MAX_FIXED_COHORTS_PER_BUILDING default

            for country_name in state.countries.keys() {
                let buildings = load_all_buildings(&temp_base, country_name);
                for building in &buildings {
                    if !building.fixed_assets.is_empty() {
                        buildings_with_cohorts += 1;
                        total_cohorts += building.fixed_assets.len();
                        for cohort in &building.fixed_assets {
                            total_cohort_units += cohort.count;
                        }
                        // Strict cap check — prevent RAM bloat.
                        assert!(
                            building.fixed_assets.len() <= cohort_cap,
                            "COHORT CAP VIOLATION at turn {}: building '{}' in '{}' has {} cohorts (max {})",
                            turn + 1, building.id, country_name, building.fixed_assets.len(), cohort_cap
                        );
                    }
                }
            }

            max_cohort_count = max_cohort_count.max(total_cohorts);
            eprintln!(
                "    Fixed assets: {} buildings | {} cohorts (max seen: {}) | {:.0} units",
                buildings_with_cohorts, total_cohorts, max_cohort_count, total_cohort_units
            );

            // === 5. PHASE 18 JUSTICE & SHADOW ECONOMY ===
            // Check that no country has negative citizen savings (drain to zero).
            for (name, country) in &state.countries {
                assert!(
                    country.budget.citizen_savings >= 0.0,
                    "NEGATIVE SAVINGS at turn {}: country '{}' has citizen_savings = {:.2}",
                    turn + 1, name, country.budget.citizen_savings
                );
                assert!(
                    country.budget.liquid_reserves.is_finite(),
                    "NAN/INF RESERVES at turn {}: country '{}' has liquid_reserves = {:.2}",
                    turn + 1, name, country.budget.liquid_reserves
                );
            }
        }
    }

    // === FINAL ASSERTIONS AFTER 100 TURNS ===
    let final_market = load_market_for_test(&temp_base);
    let final_m3 = compute_m3(&state, &final_market);
    let final_pop = compute_total_population(&state);

    eprintln!();
    eprintln!("=== SIMULATION COMPLETE: 100 TURNS ===");
    eprintln!();

    // --- 1. MONETARY CONSERVATION ---
    eprintln!("--- Monetary Conservation ---");
    eprintln!("Initial M3: {:.2}", initial_m3);
    eprintln!("Final M3:   {:.2}", final_m3);
    eprintln!("M3 multiplier range: [{:.3}x, {:.3}x]", min_m3_multiplier, max_m3_multiplier);
    eprintln!("M3 delta:   {:.2} ({:.1}%)", final_m3 - initial_m3, (final_m3 / initial_m3.max(1.0) - 1.0) * 100.0);
    assert!(final_m3 < initial_m3 * 1000.0, "Hyperinflation: final M3 = {:.2}", final_m3);
    assert!(final_m3 > initial_m3 * 0.01, "Deflationary collapse: final M3 = {:.2}", final_m3);

    // --- 2. BANKING INTEGRITY (CRITICAL — STRICT) ---
    eprintln!();
    eprintln!("--- Banking Integrity (CRITICAL) ---");
    let mut final_bank_count = 0;
    let mut final_banks_with_bs = 0;
    let mut final_banks_valid_reserves = 0;
    let mut final_total_deposits = 0.0_f64;
    let mut final_total_reserves = 0.0_f64;
    let mut final_total_loans = 0.0_f64;
    let mut banks_by_country: Vec<(String, usize, f64, f64)> = Vec::new();

    for country_name in state.countries.keys() {
        let companies = load_all_companies(&temp_base, country_name);
        let mut country_banks = 0;
        let mut country_deposits = 0.0;
        let mut country_reserves = 0.0;
        for company in &companies {
            if company.bank_type.is_some() || company.sector == Sector::Banking {
                final_bank_count += 1;
                country_banks += 1;
                if let Some(ref bs) = company.balance_sheet {
                    final_banks_with_bs += 1;
                    country_deposits += bs.deposits;
                    country_reserves += bs.reserves_at_central_bank;
                    final_total_deposits += bs.deposits;
                    final_total_reserves += bs.reserves_at_central_bank;
                    let loans: f64 = bs.loans_issued.iter().map(|l| l.outstanding_balance).sum();
                    final_total_loans += loans;
                    if bs.reserves_at_central_bank >= 0.0 && bs.deposits >= 0.0 {
                        final_banks_valid_reserves += 1;
                    }
                }
            }
        }
        banks_by_country.push((country_name.clone(), country_banks, country_deposits, country_reserves));
    }

    eprintln!("Total banks: {}", final_bank_count);
    eprintln!("Banks with balance sheet: {}", final_banks_with_bs);
    eprintln!("Banks with valid reserves: {}", final_banks_valid_reserves);
    eprintln!("Total deposits: {:.2}", final_total_deposits);
    eprintln!("Total reserves: {:.2}", final_total_reserves);
    eprintln!("Total loans outstanding: {:.2}", final_total_loans);
    eprintln!();
    eprintln!("Per-country banking summary:");
    banks_by_country.sort_by(|a, b| a.0.cmp(&b.0));
    for (name, count, deposits, reserves) in &banks_by_country {
        eprintln!("  {:<12} | Banks: {} | Deposits: {:>14.2} | Reserves: {:>14.2}", name, count, deposits, reserves);
    }

    // STRICT ASSERTIONS — no vacuous passes!
    assert!(
        final_bank_count > 0,
        "CRITICAL BANKING FAILURE: 0 banks after 100 turns. The banking sector has collapsed."
    );
    assert!(
        final_banks_with_bs > 0,
        "CRITICAL BANKING FAILURE: {} banks exist but none have balance sheets after 100 turns.",
        final_bank_count
    );
    assert!(
        final_banks_valid_reserves > 0,
        "CRITICAL BANKING FAILURE: no banks have valid (non-negative) reserves after 100 turns."
    );
    assert!(
        final_total_deposits > 0.0,
        "BANKING FAILURE: total deposits = 0 after 100 turns. Banks are not processing deposits."
    );

    // --- 3. PHASE 19 FIXED ASSETS ---
    eprintln!();
    eprintln!("--- Phase 19 Fixed Assets ---");
    eprintln!("Max cohort count seen at any checkpoint: {}", max_cohort_count);
    let mut final_total_cohorts = 0;
    let mut final_buildings_with_cohorts = 0;
    let mut final_total_units = 0.0_f64;
    for country_name in state.countries.keys() {
        let buildings = load_all_buildings(&temp_base, country_name);
        for building in &buildings {
            if !building.fixed_assets.is_empty() {
                final_buildings_with_cohorts += 1;
                final_total_cohorts += building.fixed_assets.len();
                for cohort in &building.fixed_assets {
                    final_total_units += cohort.count;
                    // Cohort count must be positive.
                    assert!(cohort.count > 0.0, "Zero-count cohort in building {}", building.id);
                    // Condition must be in valid range.
                    assert!(cohort.condition > 0.0, "Zero-condition cohort still present (should be scrapped)");
                }
            }
        }
    }
    eprintln!("Final buildings with cohorts: {}", final_buildings_with_cohorts);
    eprintln!("Final total cohorts: {}", final_total_cohorts);
    eprintln!("Final total fixed-asset units: {:.0}", final_total_units);

    // --- 4. PHASE 18 DEMOGRAPHICS & JUSTICE ---
    eprintln!();
    eprintln!("--- Phase 18 Demographics & Justice ---");
    eprintln!("Initial population: {}", initial_pop);
    eprintln!("Final population:   {}", final_pop);
    eprintln!("Population delta:   {} ({:.1}%)",
        final_pop as i64 - initial_pop as i64,
        (final_pop as f64 / initial_pop as f64 - 1.0) * 100.0);
    assert!(final_pop > 0, "Global extinction: population reached 0");
    assert!(final_pop < initial_pop * 3, "Population explosion: {}", final_pop);

    // Per-country macro summary.
    eprintln!();
    eprintln!("--- Per-Country Macroeconomic Summary (after 100 turns) ---");
    let mut country_summary: Vec<(String, f64, u64, f64, f64, f64)> = state.countries
        .iter()
        .map(|(name, c)| {
            (name.clone(), c.budget.gdp, c.budget.population,
             c.budget.liquid_reserves, c.budget.citizen_savings, c.budget.private_capital)
        })
        .collect();
    country_summary.sort_by(|a, b| a.0.cmp(&b.0));
    for (name, gdp, pop, reserves, savings, private) in &country_summary {
        eprintln!(
            "  {:<12} | GDP: {:>14.2} | Pop: {:>10} | Reserves: {:>12.2} | Savings: {:>12.2} | Private: {:>12.2}",
            name, gdp, pop, reserves, savings, private
        );
        // No negative macro values.
        assert!(*reserves >= 0.0, "Negative reserves in {}: {}", name, reserves);
        assert!(*savings >= 0.0, "Negative citizen savings in {}: {}", name, savings);
    }

    // --- 5. NO PANICS ---
    eprintln!();
    eprintln!("--- No Panics ---");
    eprintln!("Engine completed 100 turns without any panics or unhandled errors.");

    // --- 6. APOSTOLIC SEE LEDGER ---
    eprintln!();
    eprintln!("--- Apostolic See Ledger ---");
    eprintln!("Total remittances: {:.2}", final_market.apostolic_see_ledger.total_remittances);
    eprintln!("Global charity pool: {:.2}", final_market.apostolic_see_ledger.global_charity_pool);

    // Clean up.
    stdfs::remove_dir_all(&temp_base).ok();

    eprintln!();
    eprintln!("=== GREAT GOLDEN MASTER 2.0: 100-TURN SURVIVAL TEST: PASSED ===");
}
