// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 60: Zoning distribution entry (designation + percentage).
 */
export type CadastreZoningEntry = { designation: string, percentage: number, };

/**
 * Filter for the Company explorer list.
 */
export type CompanyFilter = { 
/**
 * If non-empty, only include companies whose name contains this substring (case-insensitive).
 */
search: string, 
/**
 * If non-empty, only include companies in this sector (display name).
 */
sector_filter: string, 
/**
 * Phase 54: If non-empty, only include companies in this region (region ID).
 */
region_filter: string, };

/**
 * Phase 60: Zoning plan row (public data).
 */
export type ZoningPlanRow = { region_id: string, region_name: string, plan_id: string, enacted_turn: number, implementation_progress: number, target_distribution: Array<CadastreZoningEntry>, governor_name: string, governor_trait: string, };
mber, implementation_progress: number, target_distribution: Array<CadastreZoningEntry>, governor_name: string, governor_trait: string, };
