// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 60: Owner distribution entry (owner_type + percentage).
 */
export type CadastreOwnerEntry = { owner_type: string, percentage: number, };

/**
 * Phase 60: Response wrapper for cadastre summary query.
 */
export type CadastreSummaryResponse = { rows: Array<CadastreSummaryRow>, };

/**
 * Phase 60: Cadastre summary row per region (public data — visible to all players).
 */
export type CadastreSummaryRow = { region_id: string, region_name: string, total_hectares: number, total_value: number, avg_legal_certainty: number, avg_infrastructure_access: number, zoning_distribution: Array<CadastreZoningEntry>, owner_distribution: Array<CadastreOwnerEntry>, border_conflicts: number, foreign_ownership_pct: number, };

/**
 * Phase 60: Zoning distribution entry (designation + percentage).
 */
export type CadastreZoningEntry = { designation: string, percentage: number, };
