// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Advisory council snapshot for the Parliament tab (autocracies).
 */
export type AdvisoryCouncilSnapshot = { council_type: string, members: Array<CouncilMemberRow>, aggregate_loyalty: number, coup_risk_threshold: number, coup_cooldown_until_turn: number, };

/**
 * Response for paginated bank queries.
 */
export type BankPageResponse = { rows: Array<BankRow>, total_count: number, };

/**
 * A row in the Banking tab's commercial bank list.
 */
export type BankRow = { name: string, bank_type: string, reserves: number, deposits: number, loans: number, securities: number, is_dspw: boolean, ldr: number, };

/**
 * Response for the get_banking_aggregates command.
 */
export type BankingAggregates = { total_bank_reserves: number, total_bank_deposits: number, total_bank_loans: number, total_consumer_debt: number, dspw_bank_count: number, central_bank_rate: number, m0: number, m3: number, cb_fx_reserves_total: number, cb_gold_reserves: number, };

/**
 * Phase 54: Banking history response for sparkline tooltips.
 */
export type BankingHistoryResponse = { turns: Array<number>, total_reserves: Array<number>, total_deposits: Array<number>, total_loans: Array<number>, };

/**
 * Phase 55: Board member row for governance display.
 */
export type BoardMemberRow = { vip_id: string, name: string, role: string, loyalty_to_ceo: number, appointed_turn: number, age: number, main_trait: string, };

/**
 * Phase 57: Capital gains tax summary row.
 */
export type CapitalGainsTaxRow = { entity_id: string, realized_gains: number, realized_losses: number, tax_owed: number, carried_forward_losses: number, };

/**
 * Phase 57: Capital gains tax summary response.
 */
export type CapitalGainsTaxSummary = { rows: Array<CapitalGainsTaxRow>, total_tax_collected: number, annual_tax_history: Array<number>, };

/**
 * A chamber snapshot for the Parliament tab.
 */
export type ChamberSnapshot = { name: string, total_seats: number, speaker_name: string, speaker_club: string, seat_distribution: Array<[string, number]>, };

/**
 * A parliamentary club row.
 */
export type ClubRow = { name: string, seats: number, ideology: string, is_splinter: boolean, discipline: number, 
/**
 * Phase 54: Chairperson VIP ID (if assigned).
 */
chairperson_id: string | null, 
/**
 * Phase 54: Chairperson display name.
 */
chairperson_name: string, };

/**
 * Phase 42: A committee row for the Parliament tab.
 */
export type CommitteeRow = { name: string, committee_type: string, chair: string, chair_party: string, member_count: number, bills_under_review: number, partisan_bias: number, };

/**
 * Phase 56: Commodity futures row.
 */
export type CommodityFuturesRow = { commodity_id: string, delivery_turn: number, futures_price: number, spot_price: number, basis: number, };

/**
 * Per-commodity market data for the Market tab.
 */
export type CommodityRow = { name: string, vwap: number, last_trade: number, base_price: number, net_surplus: number, 
/**
 * Phase 27: ToT (turn-over-turn) % change of net_surplus.
 */
tot_balance_change: number, 
/**
 * Phase 27: true if this commodity has any market activity (vwap, last_trade, or surplus).
 */
active: boolean, 
/**
 * Phase 43: Total sell order volume (supply).
 */
supply_volume: number, 
/**
 * Phase 43: Total buy order volume (demand).
 */
demand_volume: number, };

/**
 * Phase 56: Commodity spot price row.
 */
export type CommoditySpotRow = { commodity_id: string, spot_price: number, open_interest: bigint, history: Array<number>, };

/**
 * A full company detail for the detail view.
 */
export type CompanyDetail = { id: string, name: string, sector: string, region: string, legal_form: string, ceo_vip_id: string | null, 
/**
 * Phase 54: Resolved CEO display name from the VIP registry.
 */
ceo_name: string | null, 
/**
 * Phase 54: Resolved CEO ideology from the VIP registry.
 */
ceo_ideology: string | null, union_id: string | null, fulfilled_fte: number, fte_demand: number, average_wage: number, seasonal_state: string, furloughed_workers_count: number, wage_arrears: number, building_count: number, available_cash: number, };

/**
 * Filter for the Company explorer list.
 */
export type CompanyFilter = { 
/**
 * If non-empty, only include companies whose name contains this substring (case-insensitive).
 */
search: string, 
/**
 * If non-empty, only include companies in this sector (display name).
 */
sector_filter: string, 
/**
 * Phase 54: If non-empty, only include companies in this region (region ID).
 */
region_filter: string, };

/**
 * Response for paginated company queries.
 */
export type CompanyPageResponse = { rows: Array<CompanyRow>, total_count: number, };

/**
 * A row in the Company explorer list (compact form for table display).
 */
export type CompanyRow = { id: string, name: string, sector: string, region: string, fulfilled_fte: number, average_wage: number, seasonal_state: string, wage_arrears: number, };

/**
 * A single council member row.
 */
export type CouncilMemberRow = { vip_id: string, name: string, faction: string, loyalty: number, influence: number, };

/**
 * Building defect summary.
 */
export type DefectRow = { building_id: string, region_id: string, condition: number, structural_defect: number, };

/**
 * Geological deposit summary.
 */
export type DepositRow = { formation: string, deposit_id: string, current_reserves: number, estimated_reserves: number, quality: number, depletion_pct: number, 
/**
 * Phase 37: Number of active miners/companies extracting from this deposit.
 */
active_miners: number, };

/**
 * Summary of a household durable cohort for the region drill-down.
 */
export type DurableCohortSummary = { commodity: string, count: number, avg_condition: number, quality: number, durability: number, };

/**
 * A single dynasty member row.
 */
export type DynastyMemberRow = { vip_id: string, name: string, relation: string, age: number, succession_order: number, is_heir_apparent: boolean, };

/**
 * State of Emergency snapshot.
 */
export type EmergencySnapshot = { active: boolean, reason: string, turns_remaining: number, parliament_suspended: boolean, };

/**
 * Phase 35: Finance tab data — treasury, ministries, tax, debt, CB, banks,
 * consumer debt, and shadow economy. Reuses existing snapshot data rather
 * than creating disconnected accounting.
 */
export type FinanceSnapshot = { treasury_reserves: number, gdp: number, ministry_total_allocated: number, ministry_total_spent: number, ministry_total_cash: number, pit_revenue: number, cit_revenue: number, vat_revenue: number, wealth_tax_revenue: number, capital_gains_revenue: number, customs_revenue: number, state_property_revenue: number, pit_rate: number, cit_rate: number, vat_rate: number, wealth_tax_rate: number, capital_gains_rate: number, total_public_debt: number, debt_service: number, weighted_avg_interest_rate: number, debt_held_by_banks: number, debt_held_by_central_bank: number, debt_held_by_funds: number, debt_held_by_citizens: number, m0: number, m3: number, cb_reference_rate: number, cb_lombard_rate: number, cb_discount_rate: number, cb_rediscount_rate: number, cb_deposit_rate: number, cb_fx_reserves_total: number, cb_gold_reserves: number, cb_reserve_requirement_ratio: number, cb_omo_holdings: number, cb_liquidity_injected: number, cb_last_omo_turn: number, cb_last_omo_amount: number, total_bank_reserves: number, total_bank_deposits: number, total_bank_loans: number, total_consumer_debt: number, dspw_bank_count: number, shadow_gdp: number, pit_evaded: number, fx_basket: Array<FxBasketEntry>, 
/**
 * Phase 54: Ministry expenditure breakdown for the Finance tab.
 */
ministry_expenditure_breakdown: Array<MinistryExpenditureEntry>, };

/**
 * Phase 57: Detailed fund view for the fund detail panel.
 */
export type FundDetail = { fund_id: string, name: string, fund_type: string, nav_per_share: number, total_aum: number, manager_name: string, manager_vip_id: string, manager_trait: string, shares_outstanding: bigint, ytd_return: number, leverage_ratio: number, management_fee: number, performance_fee: number, top_holdings: Array<[string, number]>, portfolio_holdings: Array<[string, bigint, number]>, };

/**
 * Phase 57: Fund row for the investment funds UI.
 */
export type FundRow = { fund_id: string, name: string, fund_type: string, nav_per_share: number, total_aum: number, manager_name: string, manager_vip_id: string, manager_trait: string, shares_outstanding: bigint, ytd_return: number, top_holdings: Array<[string, number]>, };

/**
 * Phase 42: A single entry in the Central Bank's FX reserves basket.
 */
export type FxBasketEntry = { currency: string, amount: number, exchange_rate: number, };

/**
 * Response for the get_game_status command.
 */
export type GameStatus = { has_game: boolean, turn: number, year: number, processing: boolean, countries: Array<string>, };

/**
 * Phase 55: Governance detail for a company (board, succession, financial metrics).
 */
export type GovernanceDetail = { company_id: string, company_name: string, is_listed: boolean, shares_count: bigint, share_price: number, market_cap: number, eps: number, pe_ratio: number, dividend_yield: number, open_price: number, close_price: number, board_members: Array<BoardMemberRow>, has_board: boolean, board_independence: number, is_family_business: boolean, successor_generation: number, heir_count: number, succession_crisis: boolean, heirs: Array<BoardMemberRow>, };

/**
 * Government tab data.
 */
export type GovernmentSnapshot = { head_of_state_name: string, head_of_state_role: string, pm_name: string, pm_party: string, pm_ideology: string, cabinet: Array<MinisterRow>, state_of_emergency: EmergencySnapshot | null, political_capital: number, 
/**
 * Phase 41: Named VIPs moved from ParliamentSnapshot to GovernmentSnapshot.
 */
vips: Array<VipRow>, 
/**
 * Phase 54: Government form string for monarchy detection in the UI.
 */
government_form: string, 
/**
 * Phase 54: Royal dynasty snapshot (only populated for monarchies).
 */
royal_dynasty: RoyalDynastySnapshot | null, };

/**
 * Infrastructure link summary.
 */
export type InfrastructureRow = { link_id: string, condition: number, capacity: number, };

/**
 * KIO appeal summary.
 */
export type KioAppealRow = { id: string, appellant: string, status: string, };

/**
 * Phase 57: KNF audit finding row for the regulatory UI.
 */
export type KnfFindingRow = { entity_id: string, entity_name: string, violation_type: string, severity: number, turn: number, description: string, penalty: number, };

/**
 * Labor market summary.
 */
export type LaborSummary = { unemployment_rate: number, employed_total: number, unemployed: number, workforce: number, average_wage: number, };

/**
 * Phase 56: Detailed market view for a single listed company.
 */
export type ListedCompanyDetail = { company_id: string, name: string, sector: string, share_price: number, market_cap: number, pe_ratio: number, dividend_yield: number, eps: number, open_price: number, close_price: number, spread: number, volume: bigint, shares_count: bigint, free_float: number, recent_trades: Array<TradeRow>, };

/**
 * Phase 56: Paginated listed company page response.
 */
export type ListedCompanyPageResponse = { rows: Array<ListedCompanyRow>, total_count: number, };

/**
 * Phase 56: Listed company row for the stock exchange table.
 */
export type ListedCompanyRow = { company_id: string, name: string, sector: string, share_price: number, change_pct: number, market_cap: number, pe_ratio: number, dividend_yield: number, volume: bigint, open_price: number, close_price: number, spread: number, ceo_name: string | null, ceo_vip_id: string | null, };

/**
 * Response for the get_macro_indicators command.
 */
export type MacroIndicatorsResponse = { gdp: number, gdp_per_capita: number, population: bigint, unemployment_rate: number, inflation_rate: number, average_wage: number, money_supply_m0: number, money_supply_m3: number, consumption: number, investment: number, government_spending: number, net_exports: number, cpi: number, ppi: number, deltas: TelemetryDeltas, };

/**
 * Summary of an unfunded mandate for the region drill-down.
 */
export type MandateSummary = { description: string, required_spending: number, central_funding: number, funding_gap: number, status: string, };

/**
 * Phase 56: Market index snapshot for the stock exchange UI.
 */
export type MarketIndexSnapshot = { value: number, change_pct: number, history: Array<number>, total_market_cap: number, total_volume: bigint, advancing: number, declining: number, volatility: number, };

/**
 * Phase 53: Megaregion drill-down data for the Regions tab.
 * Analogous to `RegionDetail` but for the megaregion administrative layer.
 */
export type MegaregionDetail = { megaregion_id: string, display_name: string, country: string, member_region_ids: Array<string>, member_region_count: number, total_population: bigint, total_gdp: number, governor_name: string, governor_appointed: boolean, competence_level: string, budget_reserves: number, regional_transfers: number, development_expenditures: number, coordination_expenditures: number, budget_balance: number, };

/**
 * A minister row for the Government tab.
 */
export type MinisterRow = { ministry_name: string, minister_name: string, party: string, ideology: string, allocated_cash: number, spent_cash: number, 
/**
 * Phase 35: Current cash pocket available for spending.
 */
ministry_cash: number, };

/**
 * Phase 54: A single ministry expenditure category entry for the Finance tab.
 */
export type MinistryExpenditureEntry = { category: string, amount: number, share_pct: number, };

/**
 * OHS / casualty summary.
 */
export type OhsSummary = { total_deceased: bigint, total_disabled: bigint, total_unable_to_work_fte: number, ohs_accidents_on_projects: number, };

/**
 * Pagination request for a scrollable list view.
 */
export type PageQuery = { 
/**
 * Index of the first item to include (0-based).
 */
offset: number, 
/**
 * Maximum number of items to include in the page.
 */
limit: number, };

/**
 * Response for the get_parliament command.
 */
export type ParliamentResponse = { parliament: ParliamentSnapshot, advisory_council: AdvisoryCouncilSnapshot | null, royal_dynasty: RoyalDynastySnapshot | null, government_form: string, };

/**
 * Parliament tab data.
 */
export type ParliamentSnapshot = { chambers: Array<ChamberSnapshot>, clubs: Array<ClubRow>, recent_votes: Array<VoteRow>, legislative_queue: Array<QueueRow>, suspended: boolean, 
/**
 * Phase 34: Named VIPs (Head of State, PM, Ministers, Speakers).
 * Phase 42: Kept for backwards compat but always empty — VIPs are in GovernmentSnapshot.
 */
vips: Array<VipRow>, 
/**
 * Phase 42: Committees with chairs and member counts.
 */
committees: Array<CommitteeRow>, };

/**
 * A legislative queue row.
 */
export type QueueRow = { bill_id: string, bill_title: string, stage: string, initiator: string, };

/**
 * Full region drill-down data for the Regions tab modal.
 */
export type RegionDetail = { region_id: string, display_name: string, development_level: number, admin_status: string, head_name: string, head_type: string, 
/**
 * Phase 54: VIP ID of the regional head (for hover cards).
 */
head_vip_id: string | null, council_factions: Array<[string, number]>, 
/**
 * Phase 54: Total council seats/mandates (sum of all factions).
 */
total_council_seats: number, budget_reserves: number, budget_tax_revenue: number, budget_property_tax: number, budget_expenditures: number, budget_balance: number, debt_total: number, debt_to_revenue_ratio: number, credit_rating: string, active_mandates: Array<MandateSummary>, infrastructure_avg_condition: number, sector_employment: Array<[string, number]>, durable_cohorts: Array<DurableCohortSummary>, };

/**
 * Phase 54: A region option for the Companies tab region filter dropdown.
 */
export type RegionOption = { value: string, label: string, };

/**
 * Phase 34: A region row for the Regions tab.
 */
export type RegionRow = { id: string, display_name: string, megaregion: string, population: bigint, regional_gdp: number, gdp_per_capita: number, has_governance: boolean, liquid_reserves: number, };

/**
 * Phase 54: A role option for the VIPs tab role filter dropdown.
 */
export type RoleOption = { value: string, label: string, };

/**
 * Royal dynasty snapshot for the Parliament tab (monarchies).
 */
export type RoyalDynastySnapshot = { dynasty_name: string, current_monarch_id: string | null, current_monarch_name: string, current_regent_id: string | null, current_regent_name: string, regency_active: boolean, members: Array<DynastyMemberRow>, };

/**
 * Phase 56: Sector index snapshot.
 */
export type SectorIndexSnapshot = { sector: string, value: number, history: Array<number>, };

/**
 * Per-sector aggregation for the Sector Overview table.
 */
export type SectorRow = { sector_name: string, company_count: number, 
/**
 * Percentage share of total wages paid (proxy for GDP share).
 */
pct_gdp_share: number, 
/**
 * Total employment (sum of fulfilled_fte).
 */
total_employment: number, 
/**
 * Average wage in this sector.
 */
average_wage: number, 
/**
 * Phase 28: PMI (Purchasing Managers Index) for this sector (0-100).
 */
pmi: number, 
/**
 * Phase 28: Turn-over-Turn percentage change in employment.
 */
employment_tot: number | null, 
/**
 * Phase 28: Turn-over-Turn percentage change in average wage.
 */
wage_tot: number | null, };

/**
 * Shadow economy summary.
 */
export type ShadowEconomySummary = { total_hidden_fte: number, total_pit_evaded: number, shadow_gdp: number, };

/**
 * Phase 56: Full stock exchange response for the securities UI.
 */
export type StockExchangeResponse = { main_index: MarketIndexSnapshot, sector_indices: Array<SectorIndexSnapshot>, listed_companies: Array<ListedCompanyRow>, recent_trades: Array<TradeRow>, trading_halted: boolean, commodity_spot: Array<CommoditySpotRow>, commodity_futures: Array<CommodityFuturesRow>, };

/**
 * ToT (Turn-over-Turn) and YoY (Year-over-Year) percentage deltas
 * for key macro indicators. `None` means no historical data available.
 */
export type TelemetryDeltas = { 
/**
 * GDP ToT delta (percent).
 */
gdp_tot: number | null, 
/**
 * GDP YoY delta (percent).
 */
gdp_yoy: number | null, 
/**
 * CPI ToT delta (percent).
 */
cpi_tot: number | null, 
/**
 * CPI YoY delta (percent).
 */
cpi_yoy: number | null, 
/**
 * PPI ToT delta (percent).
 */
ppi_tot: number | null, 
/**
 * PPI YoY delta (percent).
 */
ppi_yoy: number | null, 
/**
 * M3 ToT delta (percent).
 */
m3_tot: number | null, 
/**
 * M3 YoY delta (percent).
 */
m3_yoy: number | null, 
/**
 * Unemployment ToT delta (percentage points).
 */
unemployment_tot: number | null, 
/**
 * Unemployment YoY delta (percentage points).
 */
unemployment_yoy: number | null, 
/**
 * Shadow GDP ToT delta (percent).
 */
shadow_gdp_tot: number | null, 
/**
 * Shadow GDP YoY delta (percent).
 */
shadow_gdp_yoy: number | null, 
/**
 * Corruption ToT delta (absolute change).
 */
corruption_tot: number | null, 
/**
 * Corruption YoY delta (absolute change).
 */
corruption_yoy: number | null, 
/**
 * Population ToT delta (percent).
 */
population_tot: number | null, 
/**
 * Population YoY delta (percent).
 */
population_yoy: number | null, 
/**
 * Average wage ToT delta (percent).
 */
wage_tot: number | null, 
/**
 * Average wage YoY delta (percent).
 */
wage_yoy: number | null, };

/**
 * Tender summary for the Construction tab.
 */
export type TenderRow = { id: string, 
/**
 * Phase 40: Human-readable tender name.
 */
name: string, project_type: string, 
/**
 * Phase 40: Estimated cost (value).
 */
value: number, status: string, awarded: boolean, 
/**
 * Phase 40: Contractor company ID (if awarded).
 */
contractor: string, };

/**
 * Phase 56: Recent trade row for the stock exchange UI.
 */
export type TradeRow = { instrument_id: string, buyer_id: string, seller_id: string, quantity: bigint, price: number, turn: number, };

/**
 * Treasury fields for the Finance tab.
 */
export type TreasurySummary = { gdp: number, population: bigint, liquid_reserves: number, private_capital: number, infrastructure_level: number, savings: number, };

/**
 * Response for the advance_turn command.
 */
export type TurnResult = { turn: number, year: number, status: string, };

/**
 * View parameters passed from the TUI `App` to the snapshot builder.
 * Controls pagination and filtering so the snapshot only contains the
 * visible page of data, not the entire registry.
 */
export type ViewQuery = { 
/**
 * VIP explorer pagination.
 */
vip_page: PageQuery, 
/**
 * VIP explorer filter.
 */
vip_filter: VipFilter, 
/**
 * If set, build a full dossier for this VIP ID.
 */
vip_dossier_id: string | null, 
/**
 * Company explorer pagination.
 */
company_page: PageQuery, 
/**
 * Company explorer filter.
 */
company_filter: CompanyFilter, 
/**
 * If set, build a full detail for the company with this ID.
 */
company_detail_id: string | null, 
/**
 * Banking tab bank list pagination.
 */
bank_page: PageQuery, 
/**
 * If set, build a full region drill-down detail for this region ID.
 */
region_drilldown_id: string | null, 
/**
 * Phase 53: If set, build a full megaregion drill-down detail for this megaregion ID.
 */
megaregion_drilldown_id: string | null, };

/**
 * A full VIP dossier for the detail view.
 */
export type VipDossier = { id: string, full_name: string, gender: string, age: number, health: number, incapacity: string, traits: Array<string>, main_trait: string, ideology: string, religion: string, nationality: string, dynasty: string | null, roles: Array<string>, base_influence: number, faction: string, born_turn: number, is_dead: boolean, death_turn: number | null, death_cause: string | null, acting_replacement_id: string | null, };

/**
 * A row in the VIP explorer list (compact form for table display).
 */
export type VipDossierRow = { id: string, full_name: string, roles: string, age: number, health: number, faction: string, influence: number, is_dead: boolean, main_trait: string, ideology: string, 
/**
 * Phase 54: Company name if this VIP is a CEO (for tooltip display).
 */
company_name: string | null, };

/**
 * Filter for the VIP explorer list.
 */
export type VipFilter = { 
/**
 * If true, include dead VIPs (marked with †).
 */
show_dead: boolean, 
/**
 * If non-empty, only include VIPs whose name contains this substring (case-insensitive).
 */
search: string, 
/**
 * Phase 54: If non-empty, only include VIPs with a role matching this label.
 */
role_filter: string, };

/**
 * Response for paginated VIP queries.
 */
export type VipPageResponse = { rows: Array<VipDossierRow>, total_count: number, };

/**
 * Phase 34: A named VIP row for the Parliament tab.
 */
export type VipRow = { full_name: string, party: string, role: string, ideology: string, age: number, };

/**
 * A recent vote row.
 */
export type VoteRow = { bill_id: string, bill_title: string, votes_for: number, votes_against: number, passed: boolean, turn: number, };
