//! Phase 7: State fundamental research.
//!
//! This module implements State research of Fundamental Concepts using
//! Innovation Points generated by universities.

use crate::registries::tech_tree::{TechId, TechNode, TechType};
use crate::state::treasury::Treasury;
use std::collections::HashMap;

/// Executes state fundamental research using Innovation Points.
///
/// # Arguments
/// * `treasury` - State treasury containing Innovation Points and research state
/// * `tech_tree` - Technology tree registry
/// * `current_turn` - Current simulation turn
///
/// # Returns
/// Updated treasury with research progress and newly discovered technologies
///
/// # Rules
/// * State spends Innovation Points to research Fundamental techs
/// * Only TechType::Fundamental can be researched by State
/// * Prerequisites must be met before research can begin
/// * Double-Entry: Innovation Points consumed, tech discovered
pub fn execute_state_research(
    treasury: &mut Treasury,
    tech_tree: &HashMap<TechId, TechNode>,
    _current_turn: u32,
) {
    // If already researching, continue
    if let Some(current_tech_id) = &treasury.science.researching {
        if let Some(tech_node) = tech_tree.get(current_tech_id) {
            // Verify it's a Fundamental tech
            if tech_node.tech_type != TechType::Fundamental {
                // Wrong tech type, cancel research
                treasury.science.researching = None;
                return;
            }

            // Check prerequisites
            if !prerequisites_met(tech_node, &treasury.science.discovered) {
                // Prerequisites not met, cancel research
                treasury.science.researching = None;
                return;
            }

            // Consume Innovation Points from the matching domain pool
            let points_to_consume = tech_node.cost as f64;
            let domain = tech_node.research_domain;
            let available = treasury.science.innovation_pool.get(&domain).copied().unwrap_or(0.0);
            if available >= points_to_consume {
                *treasury.science.innovation_pool.entry(domain).or_insert(0.0) -= points_to_consume;

                // Discover the technology
                treasury.science.discovered.push(current_tech_id.clone());
                treasury.science.researching = None;
            }
            // If insufficient points, research continues (points accumulate)
        }
    } else {
        // Select new Fundamental tech to research
        select_fundamental_tech(treasury, tech_tree);
    }
}

/// Selects a new Fundamental technology to research.
///
/// # Arguments
/// * `treasury` - State treasury
/// * `tech_tree` - Technology tree registry
///
/// # Rules
/// * Selects the earliest available Fundamental tech not yet discovered
/// * Prerequisites must be met
/// * Tech must be of type Fundamental
fn select_fundamental_tech(treasury: &mut Treasury, tech_tree: &HashMap<TechId, TechNode>) {
    // Collect eligible Fundamental techs and sort deterministically by (year, tech_id).
    // This ensures reproducible selection regardless of HashMap iteration order.
    let mut candidates: Vec<(&TechId, &TechNode)> = tech_tree
        .iter()
        .filter(|(_, node)| node.tech_type == TechType::Fundamental)
        .filter(|(id, _)| !treasury.science.discovered.contains(*id))
        .filter(|(_, node)| prerequisites_met(node, &treasury.science.discovered))
        .collect();
    candidates.sort_by_key(|(id, node)| (node.year, (*id).clone()));

    if let Some((tech_id, _)) = candidates.first() {
        treasury.science.researching = Some((*tech_id).clone());
    }
}

/// Checks if all prerequisites for a technology are met.
///
/// # Arguments
/// * `tech_node` - Technology node to check
/// * `discovered` - List of discovered technology IDs
///
/// # Returns
/// true if all prerequisites are met
fn prerequisites_met(tech_node: &TechNode, discovered: &[TechId]) -> bool {
    tech_node
        .prerequisites
        .iter()
        .all(|prereq| discovered.contains(prereq))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registries::tech_tree::{ResearchDomain, TechType};

    #[test]
    fn research_fundamental_tech() {
        let mut tech_tree = HashMap::new();
        tech_tree.insert(
            "tech_001".to_string(),
            TechNode {
                name: "Thermodynamics".to_string(),
                year: 1850,
                cost: 100,
                description: "Study of heat and energy".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Fundamental,
                research_domain: ResearchDomain::Engineering,
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );

        let mut treasury = Treasury {
            science: crate::state::treasury::ScienceState {
                innovation_pool: HashMap::from([(ResearchDomain::Engineering, 150.0)]),
                research_output: 0.0,
                researching: Some("tech_001".to_string()),
                discovered: Vec::new(),
                extra: serde_json::Map::new(),
            },
            liquid_reserves: 10000.0,
            ..Default::default()
        };

        execute_state_research(&mut treasury, &tech_tree, 1);

        assert!(treasury
            .science
            .discovered
            .contains(&"tech_001".to_string()));
        assert_eq!(
            treasury.science.innovation_pool[&ResearchDomain::Engineering],
            50.0
        ); // 150 - 100
        assert!(treasury.science.researching.is_none());
    }

    #[test]
    fn insufficient_points_no_discovery() {
        let mut tech_tree = HashMap::new();
        tech_tree.insert(
            "tech_001".to_string(),
            TechNode {
                name: "Thermodynamics".to_string(),
                year: 1850,
                cost: 100,
                description: "Study of heat and energy".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Fundamental,
                research_domain: ResearchDomain::Engineering,
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );

        let mut treasury = Treasury {
            science: crate::state::treasury::ScienceState {
                innovation_pool: HashMap::from([(ResearchDomain::Engineering, 50.0)]), // Insufficient
                research_output: 0.0,
                researching: Some("tech_001".to_string()),
                discovered: Vec::new(),
                extra: serde_json::Map::new(),
            },
            liquid_reserves: 10000.0,
            ..Default::default()
        };

        execute_state_research(&mut treasury, &tech_tree, 1);

        assert!(!treasury
            .science
            .discovered
            .contains(&"tech_001".to_string()));
        assert_eq!(
            treasury.science.innovation_pool[&ResearchDomain::Engineering],
            50.0
        ); // Unchanged
        assert_eq!(treasury.science.researching, Some("tech_001".to_string())); // Still researching
    }

    #[test]
    fn commercial_tech_not_researched_by_state() {
        let mut tech_tree = HashMap::new();
        tech_tree.insert(
            "tech_002".to_string(),
            TechNode {
                name: "Steel Production".to_string(),
                year: 1850,
                cost: 100,
                description: "Steel manufacturing".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Commercial, // Commercial, not Fundamental
                research_domain: ResearchDomain::Metallurgy,
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );

        let mut treasury = Treasury {
            science: crate::state::treasury::ScienceState {
                innovation_pool: HashMap::from([(ResearchDomain::Metallurgy, 150.0)]),
                research_output: 0.0,
                researching: Some("tech_002".to_string()),
                discovered: Vec::new(),
                extra: serde_json::Map::new(),
            },
            liquid_reserves: 10000.0,
            ..Default::default()
        };

        execute_state_research(&mut treasury, &tech_tree, 1);

        assert!(!treasury
            .science
            .discovered
            .contains(&"tech_002".to_string()));
        assert!(treasury.science.researching.is_none()); // Cancelled
    }

    #[test]
    fn cross_domain_cannot_substitute() {
        // A country with only Engineering points cannot research a Medicine tech.
        let mut tech_tree = HashMap::new();
        tech_tree.insert(
            "med_001".to_string(),
            TechNode {
                name: "Germ Theory".to_string(),
                year: 1880,
                cost: 100,
                description: "Microbial theory of disease".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Fundamental,
                research_domain: ResearchDomain::Medicine,
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );

        let mut treasury = Treasury {
            science: crate::state::treasury::ScienceState {
                innovation_pool: HashMap::from([(ResearchDomain::Engineering, 500.0)]), // Only Engineering
                research_output: 0.0,
                researching: Some("med_001".to_string()),
                discovered: Vec::new(),
                extra: serde_json::Map::new(),
            },
            liquid_reserves: 10000.0,
            ..Default::default()
        };

        execute_state_research(&mut treasury, &tech_tree, 1);

        // Medicine tech NOT discovered despite having plenty of Engineering points.
        assert!(!treasury
            .science
            .discovered
            .contains(&"med_001".to_string()));
    }

    #[test]
    fn select_fundamental_tech_deterministic() {
        // Multiple eligible techs — selection must be deterministic (by year, then tech_id).
        let mut tech_tree = HashMap::new();
        tech_tree.insert(
            "zzz_001".to_string(),
            TechNode {
                name: "Late Tech".to_string(),
                year: 1900,
                cost: 100,
                description: "Should not be selected first".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Fundamental,
                research_domain: ResearchDomain::Engineering,
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );
        tech_tree.insert(
            "aaa_001".to_string(),
            TechNode {
                name: "Early Tech".to_string(),
                year: 1880,
                cost: 100,
                description: "Should be selected first (earlier year)".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Fundamental,
                research_domain: ResearchDomain::Engineering,
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );

        let mut treasury = Treasury::default();
        // Run selection multiple times — must always pick the same tech.
        for _ in 0..10 {
            treasury.science.researching = None;
            execute_state_research(&mut treasury, &tech_tree, 1);
            assert_eq!(
                treasury.science.researching,
                Some("aaa_001".to_string()),
                "Selection must be deterministic"
            );
        }
    }
}
