//! Phase 7: State fundamental research.
//!
//! This module implements State research of Fundamental Concepts using
//! Innovation Points generated by universities.

use crate::registries::tech_tree::{TechId, TechNode, TechType};
use crate::state::treasury::Treasury;
use std::collections::HashMap;

/// Executes state fundamental research using Innovation Points.
///
/// # Arguments
/// * `treasury` - State treasury containing Innovation Points and research state
/// * `tech_tree` - Technology tree registry
/// * `current_turn` - Current simulation turn
///
/// # Returns
/// Updated treasury with research progress and newly discovered technologies
///
/// # Rules
/// * State spends Innovation Points to research Fundamental techs
/// * Only TechType::Fundamental can be researched by State
/// * Prerequisites must be met before research can begin
/// * Double-Entry: Innovation Points consumed, tech discovered
pub fn execute_state_research(
    treasury: &mut Treasury,
    tech_tree: &HashMap<TechId, TechNode>,
    _current_turn: u32,
) {
    // If already researching, continue
    if let Some(current_tech_id) = &treasury.science.researching {
        if let Some(tech_node) = tech_tree.get(current_tech_id) {
            // Verify it's a Fundamental tech
            if tech_node.tech_type != TechType::Fundamental {
                // Wrong tech type, cancel research
                treasury.science.researching = None;
                return;
            }

            // Check prerequisites
            if !prerequisites_met(tech_node, &treasury.science.discovered) {
                // Prerequisites not met, cancel research
                treasury.science.researching = None;
                return;
            }

            // Consume Innovation Points
            let points_to_consume = tech_node.cost as f64;
            if treasury.science.innovation_points >= points_to_consume {
                treasury.science.innovation_points -= points_to_consume;

                // Discover the technology
                treasury.science.discovered.push(current_tech_id.clone());
                treasury.science.researching = None;
            }
            // If insufficient points, research continues (points accumulate)
        }
    } else {
        // Select new Fundamental tech to research
        select_fundamental_tech(treasury, tech_tree);
    }
}

/// Selects a new Fundamental technology to research.
///
/// # Arguments
/// * `treasury` - State treasury
/// * `tech_tree` - Technology tree registry
///
/// # Rules
/// * Selects the earliest available Fundamental tech not yet discovered
/// * Prerequisites must be met
/// * Tech must be of type Fundamental
fn select_fundamental_tech(treasury: &mut Treasury, tech_tree: &HashMap<TechId, TechNode>) {
    for (tech_id, tech_node) in tech_tree.iter() {
        // Only research Fundamental techs
        if tech_node.tech_type != TechType::Fundamental {
            continue;
        }

        // Skip already discovered
        if treasury.science.discovered.contains(tech_id) {
            continue;
        }

        // Check prerequisites
        if prerequisites_met(tech_node, &treasury.science.discovered) {
            treasury.science.researching = Some(tech_id.clone());
            return;
        }
    }
}

/// Checks if all prerequisites for a technology are met.
///
/// # Arguments
/// * `tech_node` - Technology node to check
/// * `discovered` - List of discovered technology IDs
///
/// # Returns
/// true if all prerequisites are met
fn prerequisites_met(tech_node: &TechNode, discovered: &[TechId]) -> bool {
    tech_node
        .prerequisites
        .iter()
        .all(|prereq| discovered.contains(prereq))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::registries::tech_tree::TechType;

    #[test]
    fn research_fundamental_tech() {
        let mut tech_tree = HashMap::new();
        tech_tree.insert(
            "tech_001".to_string(),
            TechNode {
                name: "Thermodynamics".to_string(),
                year: 1850,
                cost: 100,
                description: "Study of heat and energy".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Fundamental,
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );

        let mut treasury = Treasury {
            science: crate::state::treasury::ScienceState {
                innovation_points: 150.0,
                researching: Some("tech_001".to_string()),
                discovered: Vec::new(),
                base_innovativeness: 1.0,
                extra: serde_json::Map::new(),
            },
            liquid_reserves: 10000.0,
            ..Default::default()
        };

        execute_state_research(&mut treasury, &tech_tree, 1);

        assert!(treasury
            .science
            .discovered
            .contains(&"tech_001".to_string()));
        assert_eq!(treasury.science.innovation_points, 50.0); // 150 - 100
        assert!(treasury.science.researching.is_none());
    }

    #[test]
    fn insufficient_points_no_discovery() {
        let mut tech_tree = HashMap::new();
        tech_tree.insert(
            "tech_001".to_string(),
            TechNode {
                name: "Thermodynamics".to_string(),
                year: 1850,
                cost: 100,
                description: "Study of heat and energy".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Fundamental,
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );

        let mut treasury = Treasury {
            science: crate::state::treasury::ScienceState {
                innovation_points: 50.0, // Insufficient
                researching: Some("tech_001".to_string()),
                discovered: Vec::new(),
                base_innovativeness: 1.0,
                extra: serde_json::Map::new(),
            },
            liquid_reserves: 10000.0,
            ..Default::default()
        };

        execute_state_research(&mut treasury, &tech_tree, 1);

        assert!(!treasury
            .science
            .discovered
            .contains(&"tech_001".to_string()));
        assert_eq!(treasury.science.innovation_points, 50.0); // Unchanged
        assert_eq!(treasury.science.researching, Some("tech_001".to_string())); // Still researching
    }

    #[test]
    fn commercial_tech_not_researched_by_state() {
        let mut tech_tree = HashMap::new();
        tech_tree.insert(
            "tech_002".to_string(),
            TechNode {
                name: "Steel Production".to_string(),
                year: 1850,
                cost: 100,
                description: "Steel manufacturing".to_string(),
                unlocks_methods: HashMap::new(),
                unlocks_projects: Vec::new(),
                prerequisites: Vec::new(),
                tech_type: TechType::Commercial, // Commercial, not Fundamental
                patent_duration_turns: 240,
                royalty_vwap_ratio: 0.05,
            },
        );

        let mut treasury = Treasury {
            science: crate::state::treasury::ScienceState {
                innovation_points: 150.0,
                researching: Some("tech_002".to_string()),
                discovered: Vec::new(),
                base_innovativeness: 1.0,
                extra: serde_json::Map::new(),
            },
            liquid_reserves: 10000.0,
            ..Default::default()
        };

        execute_state_research(&mut treasury, &tech_tree, 1);

        assert!(!treasury
            .science
            .discovered
            .contains(&"tech_002".to_string()));
        assert!(treasury.science.researching.is_none()); // Cancelled
    }
}
